import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:palengkego/core/config/app_config.dart';
import 'package:palengkego/firebase_options.dart';

// ─────────────────────────────────────────────────────────────────────────────
// Firebase SDK instance providers
// Firebase Auth + FCM only. Firestore and Storage replaced by Supabase.
// ─────────────────────────────────────────────────────────────────────────────

/// Provider for Firebase Auth instance.
final firebaseAuthProvider = Provider<FirebaseAuth>((ref) {
  return FirebaseAuth.instance;
});

/// Provider for Firebase Messaging instance.
final firebaseMessagingProvider = Provider<FirebaseMessaging>((ref) {
  return FirebaseMessaging.instance;
});

/// Convenience provider — reads whether Firebase is enabled via
/// [AppConfig]. Always returns false in current architecture where
/// Supabase is the primary database.
final firebaseEnabledProvider = Provider<bool>((ref) {
  return ref.watch(appConfigProvider).firebaseEnabled;
});

// ─────────────────────────────────────────────────────────────────────────────
// FirebaseService — handles app startup initialization (Auth + FCM only)
// ─────────────────────────────────────────────────────────────────────────────

class FirebaseService {
  /// Initializes Firebase with the platform options generated by
  /// `flutterfire configure` (`lib/firebase_options.dart`, gitignored).
  /// Only Auth and FCM are initialized — Firestore and Storage are replaced
  /// by Supabase PostgreSQL and Supabase Storage respectively.
  ///
  /// Should always be called — Supabase handles all data operations.
  /// Throws when Firebase cannot be initialized — callers decide whether
  /// that is fatal (production) or a log-and-continue (development).
  static Future<void> initialize() async {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  }
}
