import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:cloud_functions/cloud_functions.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:firebase_app_check/firebase_app_check.dart';
import 'package:flutter/foundation.dart';
import 'package:palengkego/core/config/app_config.dart';
import 'package:palengkego/firebase_options.dart';

// ─────────────────────────────────────────────────────────────────────────────
// Firebase SDK instance providers
// These are safe to keep — they are only accessed when Firebase is actually
// initialized (i.e. when firebaseEnabled == true).
// ─────────────────────────────────────────────────────────────────────────────

/// Provider for Firebase Auth instance.
final firebaseAuthProvider = Provider<FirebaseAuth>((ref) {
  return FirebaseAuth.instance;
});

/// Provider for Cloud Firestore instance.
final firestoreProvider = Provider<FirebaseFirestore>((ref) {
  return FirebaseFirestore.instance;
});

/// Provider for Cloud Functions (HTTPS callables) — the trusted backend path
/// used by the order and review repositories.
final firebaseFunctionsProvider = Provider<FirebaseFunctions>((ref) {
  return FirebaseFunctions.instance;
});

/// Provider for Firebase Storage instance.
final firebaseStorageProvider = Provider<FirebaseStorage>((ref) {
  return FirebaseStorage.instance;
});

/// Convenience provider — reads the FIREBASE_ENABLED dart-define flag
/// from [AppConfig] so any provider can check it without importing AppConfig.
final firebaseEnabledProvider = Provider<bool>((ref) {
  return ref.watch(appConfigProvider).firebaseEnabled;
});

// ─────────────────────────────────────────────────────────────────────────────
// FirebaseService — handles app startup initialization
// ─────────────────────────────────────────────────────────────────────────────

class FirebaseService {
  /// Initializes Firebase with the platform options generated by
  /// `flutterfire configure` (`lib/firebase_options.dart`, gitignored).
  ///
  /// Should only be called when [AppConfig.firebaseEnabled] is true.
  /// Throws when Firebase cannot be initialized — callers decide whether
  /// that is fatal (production) or a log-and-continue (development).
  static Future<void> initialize() async {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    await _activateAppCheck();
  }

  /// Attaches App Check tokens to all outgoing Firebase requests (callables,
  /// Firestore, Storage). Debug builds use the debug provider; release builds
  /// require Play Integrity (Android) / App Attest (iOS) to be enabled in the
  /// Firebase console. The backend only ENFORCES tokens when the
  /// APP_CHECK_ENFORCED config flag is set — see functions/src/security.ts.
  static Future<void> _activateAppCheck() async {
    try {
      await FirebaseAppCheck.instance.activate(
        providerAndroid: kReleaseMode
            ? const AndroidPlayIntegrityProvider()
            : const AndroidDebugProvider(),
        providerApple: kReleaseMode
            ? const AppleAppAttestProvider()
            : const AppleDebugProvider(),
      );
      FirebaseAppCheck.instance.setTokenAutoRefreshEnabled(true);
    } catch (e) {
      debugPrint('App Check activation skipped: $e');
    }
  }
}
