-- Append remaining recipes after MAX(id) — no explicit id, identity generates
-- Source: FILIPINO_DESSERT_FINAL.md + FILIPINO_SNACKS_FINAL.md (tail after first 48)
-- Run after 20250915000000_fill_recipe_gaps.sql

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Suman sa Lihiya', 'Dessert', '30 min', 'Medium', '', '1 person', '400 kcal', NULL, '[{"name": "1/2 cups glutinous rice", "description": "1/2 cups glutinous rice"}, {"name": "1/4 tbsp lye water", "description": "1/4 tbsp lye water"}, {"name": "1 cups water", "description": "1 cups water"}, {"name": "Banana leaves for wrapping", "description": "Banana leaves for wrapping"}, {"name": "Brown sugar or latik for serving", "description": "Brown sugar or latik for serving"}, {"name": "Glutinous Rice -> short-grain rice", "description": "Glutinous Rice -> short-grain rice"}, {"name": "Lye Water -> food-grade lye water is essential; do not substitute with household chemicals", "description": "Lye Water -> food-grade lye water is essential; do not substitute with household chemicals"}, {"name": "Banana Leaves -> parchment paper for lining", "description": "Banana Leaves -> parchment paper for lining"}, {"name": "Brown Sugar -> white sugar", "description": "Brown Sugar -> white sugar"}]'::jsonb, '[{"title": "Step 1", "description": "Wash the glutinous rice thoroughly."}, {"title": "Step 2", "description": "Soak the rice in water mixed with lye water for 2 hours."}, {"title": "Step 3", "description": "Drain the rice well."}, {"title": "Step 4", "description": "Wrap portions of the rice in banana leaves and tie securely."}, {"title": "Step 5", "description": "Boil for 11/2–2 hours until tender."}, {"title": "Step 6", "description": "Remove and drain."}, {"title": "Step 7", "description": "Serve with brown sugar or latik."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Ginataang Halo-Halo', 'Dessert', '30 min', 'Medium', '', '1 person', '650 kcal', NULL, '[{"name": "1/2 cups coconut milk", "description": "1/2 cups coconut milk"}, {"name": "1/4 cup coconut cream", "description": "1/4 cup coconut cream"}, {"name": "1/2 saba bananas, sliced", "description": "1/2 saba bananas, sliced"}, {"name": "1/4 cup sweet potatoes, cubed", "description": "1/4 cup sweet potatoes, cubed"}, {"name": "1/4 cup jackfruit strips", "description": "1/4 cup jackfruit strips"}, {"name": "1/8 cup cooked tapioca pearls", "description": "1/8 cup cooked tapioca pearls"}, {"name": "1/8 cup glutinous rice balls", "description": "1/8 cup glutinous rice balls"}, {"name": "1/8 cup brown sugar", "description": "1/8 cup brown sugar"}, {"name": "Coconut Milk -> evaporated milk or fresh milk", "description": "Coconut Milk -> evaporated milk or fresh milk"}, {"name": "Coconut Cream -> thick coconut milk or all-purpose cream", "description": "Coconut Cream -> thick coconut milk or all-purpose cream"}, {"name": "Saba Bananas -> ripe plantain", "description": "Saba Bananas -> ripe plantain"}, {"name": "Sweet Potatoes -> pumpkin or another sweet potato variety", "description": "Sweet Potatoes -> pumpkin or another sweet potato variety"}]'::jsonb, '[{"title": "Step 1", "description": "Heat the coconut milk in a saucepan."}, {"title": "Step 2", "description": "Add the sweet potatoes and cook until almost tender."}, {"title": "Step 3", "description": "Stir in the glutinous rice balls and cook until they float."}, {"title": "Step 4", "description": "Add the saba bananas, jackfruit, and brown sugar."}, {"title": "Step 5", "description": "Mix in the cooked tapioca pearls."}, {"title": "Step 6", "description": "Pour in the coconut cream and simmer for 3–5 minutes."}, {"title": "Step 7", "description": "Serve warm."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Minatamis na Kamoteng Kahoy', 'Dessert', '30 min', 'Easy', '', '1 person', '500 kcal', NULL, '[{"name": "1/4 kg cassava, peeled and sliced", "description": "1/4 kg cassava, peeled and sliced"}, {"name": "1/4 cup brown sugar", "description": "1/4 cup brown sugar"}, {"name": "1 cups water", "description": "1 cups water"}, {"name": "1/4 pandan leaf", "description": "1/4 pandan leaf"}, {"name": "1/4 tsp vanilla extract (optional)", "description": "1/4 tsp vanilla extract (optional)"}, {"name": "Brown Sugar -> white sugar", "description": "Brown Sugar -> white sugar"}, {"name": "Pandan Leaf -> pandan extract or vanilla", "description": "Pandan Leaf -> pandan extract or vanilla"}, {"name": "Vanilla Extract -> vanilla essence or omit", "description": "Vanilla Extract -> vanilla essence or omit"}]'::jsonb, '[{"title": "Step 1", "description": "Place the water, brown sugar, and pandan leaf in a pot."}, {"title": "Step 2", "description": "Bring to a boil until the sugar dissolves."}, {"title": "Step 3", "description": "Add the cassava pieces."}, {"title": "Step 4", "description": "Simmer until the cassava becomes tender."}, {"title": "Step 5", "description": "Stir in the vanilla extract if desired."}, {"title": "Step 6", "description": "Remove from the heat."}, {"title": "Step 7", "description": "Serve warm or chilled."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Buko Pandan Ice Candy', 'Dessert', '30 min', 'Easy', '', '1 person', '300 kcal', NULL, '[{"name": "1/2 cups young coconut strips", "description": "1/2 cups young coconut strips"}, {"name": "1/4 cup evaporated milk", "description": "1/4 cup evaporated milk"}, {"name": "1/4 cup coconut milk", "description": "1/4 cup coconut milk"}, {"name": "1/8 cup condensed milk", "description": "1/8 cup condensed milk"}, {"name": "1/4 tsp pandan flavoring", "description": "1/4 tsp pandan flavoring"}, {"name": "Ice candy plastic bags", "description": "Ice candy plastic bags"}, {"name": "Young Coconut -> canned young coconut, drained", "description": "Young Coconut -> canned young coconut, drained"}, {"name": "Evaporated Milk -> fresh milk", "description": "Evaporated Milk -> fresh milk"}, {"name": "Coconut Milk -> evaporated milk or fresh milk", "description": "Coconut Milk -> evaporated milk or fresh milk"}, {"name": "Condensed Milk -> evaporated milk + sugar", "description": "Condensed Milk -> evaporated milk + sugar"}]'::jsonb, '[{"title": "Step 1", "description": "Combine the evaporated milk, coconut milk, condensed milk, and pandan flavoring."}, {"title": "Step 2", "description": "Stir until well mixed."}, {"title": "Step 3", "description": "Add the young coconut strips."}, {"title": "Step 4", "description": "Pour the mixture into ice candy bags."}, {"title": "Step 5", "description": "Tie the bags securely."}, {"title": "Step 6", "description": "Freeze overnight."}, {"title": "Step 7", "description": "Serve frozen."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Saging na May Latik', 'Dessert', '30 min', 'Easy', '', '1 person', '500 kcal', NULL, '[{"name": "1.5 ripe saba bananas", "description": "1.5 ripe saba bananas"}, {"name": "1/2 cups coconut milk", "description": "1/2 cups coconut milk"}, {"name": "1/8 cup brown sugar", "description": "1/8 cup brown sugar"}, {"name": "1/4 cup coconut cream", "description": "1/4 cup coconut cream"}, {"name": "1/8 tsp salt", "description": "1/8 tsp salt"}, {"name": "Saba Bananas -> ripe plantain", "description": "Saba Bananas -> ripe plantain"}, {"name": "Coconut Milk -> evaporated milk or fresh milk", "description": "Coconut Milk -> evaporated milk or fresh milk"}, {"name": "Brown Sugar -> white sugar", "description": "Brown Sugar -> white sugar"}, {"name": "Coconut Cream -> thick coconut milk or all-purpose cream", "description": "Coconut Cream -> thick coconut milk or all-purpose cream"}]'::jsonb, '[{"title": "Step 1", "description": "Heat the coconut milk in a saucepan."}, {"title": "Step 2", "description": "Add the brown sugar and salt."}, {"title": "Step 3", "description": "Place the saba bananas into the mixture."}, {"title": "Step 4", "description": "Simmer until the bananas are tender."}, {"title": "Step 5", "description": "Cook the coconut cream separately until it forms golden latik."}, {"title": "Step 6", "description": "Spoon the latik over the cooked bananas."}, {"title": "Step 7", "description": "Serve warm."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Ube Buchi', 'Dessert', '30 min', 'Medium', '', '1 person', '600 kcal', NULL, '[{"name": "1/2 cups glutinous rice flour", "description": "1/2 cups glutinous rice flour"}, {"name": "3/16 cup warm water", "description": "3/16 cup warm water"}, {"name": "1/4 cup ube halaya", "description": "1/4 cup ube halaya"}, {"name": "1/4 cup sesame seeds", "description": "1/4 cup sesame seeds"}, {"name": "Cooking oil for frying", "description": "Cooking oil for frying"}, {"name": "Glutinous Rice Flour -> rice flour + a little cornstarch", "description": "Glutinous Rice Flour -> rice flour + a little cornstarch"}, {"name": "Ube Halaya -> mashed purple sweet potato + sugar", "description": "Ube Halaya -> mashed purple sweet potato + sugar"}]'::jsonb, '[{"title": "Step 1", "description": "Mix the glutinous rice flour and warm water into a smooth dough."}, {"title": "Step 2", "description": "Divide the dough into equal portions."}, {"title": "Step 3", "description": "Flatten each piece and fill with ube halaya."}, {"title": "Step 4", "description": "Seal and roll into balls."}, {"title": "Step 5", "description": "Coat each ball with sesame seeds."}, {"title": "Step 6", "description": "Deep-fry over low to medium heat until golden brown."}, {"title": "Step 7", "description": "Drain excess oil and serve warm."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Buko Pie Cups', 'Dessert', '30 min', 'Medium', '', '1 person', '500 kcal', NULL, '[{"name": "1/2 cups young coconut meat, shredded", "description": "1/2 cups young coconut meat, shredded"}, {"name": "1/4 package ready-made pie crust", "description": "1/4 package ready-made pie crust"}, {"name": "1/4 cup evaporated milk", "description": "1/4 cup evaporated milk"}, {"name": "1/8 cup condensed milk", "description": "1/8 cup condensed milk"}, {"name": "1/2 tbsp cornstarch", "description": "1/2 tbsp cornstarch"}, {"name": "1/4 egg, beaten", "description": "1/4 egg, beaten"}, {"name": "Young Coconut -> canned young coconut, drained", "description": "Young Coconut -> canned young coconut, drained"}, {"name": "Pie Crust -> store-bought pastry crust", "description": "Pie Crust -> store-bought pastry crust"}, {"name": "Evaporated Milk -> fresh milk", "description": "Evaporated Milk -> fresh milk"}, {"name": "Condensed Milk -> evaporated milk + sugar", "description": "Condensed Milk -> evaporated milk + sugar"}, {"name": "Cornstarch -> all-purpose flour", "description": "Cornstarch -> all-purpose flour"}]'::jsonb, '[{"title": "Step 1", "description": "Preheat the oven to 180°C (350°F)."}, {"title": "Step 2", "description": "Line muffin tins with small pieces of pie crust."}, {"title": "Step 3", "description": "Cook the young coconut, evaporated milk, condensed milk, and cornstarch until thick."}, {"title": "Step 4", "description": "Spoon the filling into each pastry shell."}, {"title": "Step 5", "description": "Brush the edges with beaten egg."}, {"title": "Step 6", "description": "Bake for 20–25 minutes or until golden brown."}, {"title": "Step 7", "description": "Cool slightly before serving."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Espasol', 'Dessert', '30 min', 'Medium', '', '1 person', '450 kcal', NULL, '[{"name": "1/2 cups glutinous rice flour", "description": "1/2 cups glutinous rice flour"}, {"name": "1/2 cups coconut milk", "description": "1/2 cups coconut milk"}, {"name": "3/16 cup sugar", "description": "3/16 cup sugar"}, {"name": "1/8 cup toasted rice flour", "description": "1/8 cup toasted rice flour"}, {"name": "1/16 tsp salt", "description": "1/16 tsp salt"}, {"name": "Glutinous Rice Flour -> rice flour + a little cornstarch", "description": "Glutinous Rice Flour -> rice flour + a little cornstarch"}, {"name": "Coconut Milk -> evaporated milk or fresh milk", "description": "Coconut Milk -> evaporated milk or fresh milk"}]'::jsonb, '[{"title": "Step 1", "description": "Heat the coconut milk in a saucepan over low heat."}, {"title": "Step 2", "description": "Add the sugar and salt, stirring until dissolved."}, {"title": "Step 3", "description": "Gradually add the glutinous rice flour while stirring continuously."}, {"title": "Step 4", "description": "Cook until the mixture becomes thick and smooth."}, {"title": "Step 5", "description": "Transfer to a tray dusted with toasted rice flour."}, {"title": "Step 6", "description": "Roll into logs and coat with more toasted rice flour."}, {"title": "Step 7", "description": "Slice into serving pieces and serve."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Buko Macaroni Salad', 'Dessert', '30 min', 'Easy', '', '1 person', '550 kcal', NULL, '[{"name": "1/2 cups elbow macaroni", "description": "1/2 cups elbow macaroni"}, {"name": "1/4 cup young coconut strips", "description": "1/4 cup young coconut strips"}, {"name": "1/4 cup fruit cocktail, drained", "description": "1/4 cup fruit cocktail, drained"}, {"name": "1/4 cup all-purpose cream", "description": "1/4 cup all-purpose cream"}, {"name": "1/4 can condensed milk", "description": "1/4 can condensed milk"}, {"name": "1/8 cup cheese cubes", "description": "1/8 cup cheese cubes"}, {"name": "Young Coconut -> canned young coconut, drained", "description": "Young Coconut -> canned young coconut, drained"}, {"name": "Fruit Cocktail -> mixed canned fruits", "description": "Fruit Cocktail -> mixed canned fruits"}, {"name": "All-Purpose Cream -> whipping cream or chilled evaporated milk", "description": "All-Purpose Cream -> whipping cream or chilled evaporated milk"}, {"name": "Condensed Milk -> evaporated milk + sugar", "description": "Condensed Milk -> evaporated milk + sugar"}, {"name": "Cheese -> quick-melt cheese or mild cheddar", "description": "Cheese -> quick-melt cheese or mild cheddar"}]'::jsonb, '[{"title": "Step 1", "description": "Cook the macaroni according to the package instructions and drain."}, {"title": "Step 2", "description": "Allow the macaroni to cool completely."}, {"title": "Step 3", "description": "Combine the macaroni, young coconut, fruit cocktail, and cheese cubes."}, {"title": "Step 4", "description": "Add the all-purpose cream and condensed milk."}, {"title": "Step 5", "description": "Mix gently until evenly coated."}, {"title": "Step 6", "description": "Refrigerate for at least 4 hours."}, {"title": "Step 7", "description": "Serve chilled."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Tinutong na Mais', 'Dessert', '30 min', 'Medium', '', '1 person', '500 kcal', NULL, '[{"name": "1/2 cups roasted corn kernels", "description": "1/2 cups roasted corn kernels"}, {"name": "3/4 cups coconut milk", "description": "3/4 cups coconut milk"}, {"name": "1/8 cup brown sugar", "description": "1/8 cup brown sugar"}, {"name": "1/16 tsp salt", "description": "1/16 tsp salt"}, {"name": "1/4 pandan leaf (optional)", "description": "1/4 pandan leaf (optional)"}, {"name": "Coconut Milk -> evaporated milk or fresh milk", "description": "Coconut Milk -> evaporated milk or fresh milk"}, {"name": "Brown Sugar -> white sugar", "description": "Brown Sugar -> white sugar"}, {"name": "Pandan Leaf -> pandan extract or vanilla", "description": "Pandan Leaf -> pandan extract or vanilla"}]'::jsonb, '[{"title": "Step 1", "description": "Heat the coconut milk in a saucepan."}, {"title": "Step 2", "description": "Add the roasted corn and pandan leaf."}, {"title": "Step 3", "description": "Stir in the brown sugar and salt."}, {"title": "Step 4", "description": "Simmer over low heat for 15–20 minutes."}, {"title": "Step 5", "description": "Remove the pandan leaf."}, {"title": "Step 6", "description": "Allow the mixture to cool slightly."}, {"title": "Step 7", "description": "Serve warm."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Sweet Ginataang Mais', 'Dessert', '30 min', 'Easy', '', '1 person', '450 kcal', NULL, '[{"name": "1/2 cups sweet corn kernels", "description": "1/2 cups sweet corn kernels"}, {"name": "1/2 cups coconut milk", "description": "1/2 cups coconut milk"}, {"name": "1/8 cup coconut cream", "description": "1/8 cup coconut cream"}, {"name": "0.083 cup sugar", "description": "0.083 cup sugar"}, {"name": "1/16 tsp salt", "description": "1/16 tsp salt"}, {"name": "Coconut Milk -> evaporated milk or fresh milk", "description": "Coconut Milk -> evaporated milk or fresh milk"}, {"name": "Coconut Cream -> thick coconut milk or all-purpose cream", "description": "Coconut Cream -> thick coconut milk or all-purpose cream"}]'::jsonb, '[{"title": "Step 1", "description": "Pour the coconut milk into a saucepan and bring to a gentle simmer."}, {"title": "Step 2", "description": "Add the sweet corn kernels."}, {"title": "Step 3", "description": "Stir in the sugar and salt."}, {"title": "Step 4", "description": "Simmer for 10 minutes."}, {"title": "Step 5", "description": "Add the coconut cream."}, {"title": "Step 6", "description": "Cook for another 3 minutes."}, {"title": "Step 7", "description": "Serve warm."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Pinipig Crunch Cups', 'Dessert', '30 min', 'Easy', '', '1 person', '500 kcal', NULL, '[{"name": "1/2 cups toasted pinipig", "description": "1/2 cups toasted pinipig"}, {"name": "1/2 cups mini marshmallows", "description": "1/2 cups mini marshmallows"}, {"name": "1/16 cup butter", "description": "1/16 cup butter"}, {"name": "1/8 cup melted chocolate", "description": "1/8 cup melted chocolate"}, {"name": "Butter -> margarine", "description": "Butter -> margarine"}]'::jsonb, '[{"title": "Step 1", "description": "Melt the butter in a saucepan over low heat."}, {"title": "Step 2", "description": "Add the marshmallows and stir until melted."}, {"title": "Step 3", "description": "Fold in the toasted pinipig."}, {"title": "Step 4", "description": "Spoon the mixture into paper cups."}, {"title": "Step 5", "description": "Drizzle with melted chocolate."}, {"title": "Step 6", "description": "Refrigerate for 30 minutes."}, {"title": "Step 7", "description": "Serve chilled."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Buko Lychee Salad', 'Dessert', '30 min', 'Easy', '', '1 person', '550 kcal', NULL, '[{"name": "1/2 cups young coconut strips", "description": "1/2 cups young coconut strips"}, {"name": "1/4 can lychees, drained", "description": "1/4 can lychees, drained"}, {"name": "1/4 cup all-purpose cream", "description": "1/4 cup all-purpose cream"}, {"name": "1/4 can condensed milk", "description": "1/4 can condensed milk"}, {"name": "1/8 cup nata de coco", "description": "1/8 cup nata de coco"}, {"name": "Young Coconut -> canned young coconut, drained", "description": "Young Coconut -> canned young coconut, drained"}, {"name": "All-Purpose Cream -> whipping cream or chilled evaporated milk", "description": "All-Purpose Cream -> whipping cream or chilled evaporated milk"}, {"name": "Condensed Milk -> evaporated milk + sugar", "description": "Condensed Milk -> evaporated milk + sugar"}, {"name": "Nata De Coco -> jelly cubes", "description": "Nata De Coco -> jelly cubes"}]'::jsonb, '[{"title": "Step 1", "description": "Drain the lychees and nata de coco."}, {"title": "Step 2", "description": "Combine the young coconut, lychees, and nata de coco."}, {"title": "Step 3", "description": "Add the all-purpose cream and condensed milk."}, {"title": "Step 4", "description": "Fold gently until well combined."}, {"title": "Step 5", "description": "Transfer to a serving container."}, {"title": "Step 6", "description": "Refrigerate for at least 3 hours."}, {"title": "Step 7", "description": "Serve chilled."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Cassava Coconut Balls', 'Dessert', '30 min', 'Easy', '', '1 person', '350 kcal', NULL, '[{"name": "1/2 cups grated cassava", "description": "1/2 cups grated cassava"}, {"name": "1/8 cup grated coconut", "description": "1/8 cup grated coconut"}, {"name": "1/8 cup condensed milk", "description": "1/8 cup condensed milk"}, {"name": "1/16 cup sugar", "description": "1/16 cup sugar"}, {"name": "Extra grated coconut for coating", "description": "Extra grated coconut for coating"}, {"name": "Grated Cassava -> frozen grated cassava, thawed and drained", "description": "Grated Cassava -> frozen grated cassava, thawed and drained"}, {"name": "Grated Coconut -> desiccated coconut", "description": "Grated Coconut -> desiccated coconut"}, {"name": "Condensed Milk -> evaporated milk + sugar", "description": "Condensed Milk -> evaporated milk + sugar"}]'::jsonb, '[{"title": "Step 1", "description": "Steam the grated cassava until fully cooked."}, {"title": "Step 2", "description": "Allow it to cool slightly."}, {"title": "Step 3", "description": "Mix in the condensed milk, sugar, and grated coconut."}, {"title": "Step 4", "description": "Form the mixture into small balls."}, {"title": "Step 5", "description": "Roll each ball in grated coconut."}, {"title": "Step 6", "description": "Chill for 30 minutes."}, {"title": "Step 7", "description": "Serve cold."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Langka Cream Cups', 'Dessert', '30 min', 'Easy', '', '1 person', '350 kcal', NULL, '[{"name": "1/2 cups ripe jackfruit, sliced", "description": "1/2 cups ripe jackfruit, sliced"}, {"name": "1/4 cup all-purpose cream", "description": "1/4 cup all-purpose cream"}, {"name": "1/8 cup condensed milk", "description": "1/8 cup condensed milk"}, {"name": "1/16 cup crushed graham crackers", "description": "1/16 cup crushed graham crackers"}, {"name": "Mint leaves for garnish (optional)", "description": "Mint leaves for garnish (optional)"}, {"name": "Jackfruit -> canned jackfruit, drained", "description": "Jackfruit -> canned jackfruit, drained"}, {"name": "All-Purpose Cream -> whipping cream or chilled evaporated milk", "description": "All-Purpose Cream -> whipping cream or chilled evaporated milk"}, {"name": "Condensed Milk -> evaporated milk + sugar", "description": "Condensed Milk -> evaporated milk + sugar"}, {"name": "Graham Crackers -> digestive biscuits or plain cookies", "description": "Graham Crackers -> digestive biscuits or plain cookies"}]'::jsonb, '[{"title": "Step 1", "description": "Chill the all-purpose cream before using."}, {"title": "Step 2", "description": "Mix the cream and condensed milk until smooth."}, {"title": "Step 3", "description": "Layer the jackfruit slices into serving cups."}, {"title": "Step 4", "description": "Spoon the cream mixture over the jackfruit."}, {"title": "Step 5", "description": "Sprinkle crushed graham crackers on top."}, {"title": "Step 6", "description": "Refrigerate for at least 2 hours."}, {"title": "Step 7", "description": "Garnish with mint leaves before serving."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Turon', 'Snack', '30 min', 'Easy', '', '1 person', '250 kcal', NULL, '[{"name": "6 ripe saba bananas, halved lengthwise", "description": "6 ripe saba bananas, halved lengthwise"}, {"name": "1 cup ripe langka (jackfruit), sliced", "description": "1 cup ripe langka (jackfruit), sliced"}, {"name": "12 lumpia wrappers", "description": "12 lumpia wrappers"}, {"name": "1 cup brown sugar", "description": "1 cup brown sugar"}, {"name": "Cooking oil for frying", "description": "Cooking oil for frying"}, {"name": "Water for sealing wrappers", "description": "Water for sealing wrappers"}]'::jsonb, '[{"title": "Step 1", "description": "Roll each banana in brown sugar until coated."}, {"title": "Step 2", "description": "Place one banana and a few slices of jackfruit on a lumpia wrapper."}, {"title": "Step 3", "description": "Fold the sides inward and roll tightly."}, {"title": "Step 4", "description": "Seal the edge with water."}, {"title": "Step 5", "description": "Heat oil over medium heat."}, {"title": "Step 6", "description": "Fry the turon until golden brown and caramelized, about 5–7 minutes."}, {"title": "Step 7", "description": "Drain on paper towels and serve warm."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Banana Cue', 'Snack', '30 min', 'Easy', '', '1 person', '220 kcal', NULL, '[{"name": "8 ripe saba bananas", "description": "8 ripe saba bananas"}, {"name": "1 cup brown sugar", "description": "1 cup brown sugar"}, {"name": "3 cups cooking oil", "description": "3 cups cooking oil"}, {"name": "8 bamboo skewers", "description": "8 bamboo skewers"}]'::jsonb, '[{"title": "Step 1", "description": "Heat the cooking oil in a deep pan."}, {"title": "Step 2", "description": "Fry the saba bananas until lightly golden."}, {"title": "Step 3", "description": "Sprinkle the brown sugar evenly into the oil."}, {"title": "Step 4", "description": "Allow the sugar to melt and coat the bananas."}, {"title": "Step 5", "description": "Turn the bananas until fully coated with caramel."}, {"title": "Step 6", "description": "Remove and drain briefly."}, {"title": "Step 7", "description": "Skewer each banana and serve warm."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Camote Cue', 'Snack', '30 min', 'Easy', '', '1 person', '250 kcal', NULL, '[{"name": "500g sweet potatoes (camote), peeled and sliced", "description": "500g sweet potatoes (camote), peeled and sliced"}, {"name": "1 cup brown sugar", "description": "1 cup brown sugar"}, {"name": "3 cups cooking oil", "description": "3 cups cooking oil"}, {"name": "Bamboo skewers", "description": "Bamboo skewers"}]'::jsonb, '[{"title": "Step 1", "description": "Heat oil over medium heat."}, {"title": "Step 2", "description": "Fry the camote slices until tender."}, {"title": "Step 3", "description": "Sprinkle brown sugar into the oil."}, {"title": "Step 4", "description": "Let the sugar melt and coat the camote evenly."}, {"title": "Step 5", "description": "Continue frying until caramelized."}, {"title": "Step 6", "description": "Remove and drain excess oil."}, {"title": "Step 7", "description": "Thread onto skewers and serve."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Maruya', 'Snack', '30 min', 'Easy', '', '1 person', '300 kcal', NULL, '[{"name": "6 ripe saba bananas", "description": "6 ripe saba bananas"}, {"name": "1 cup all-purpose flour", "description": "1 cup all-purpose flour"}, {"name": "1 egg", "description": "1 egg"}, {"name": "1/2 cup milk", "description": "1/2 cup milk"}, {"name": "2 tbsp sugar", "description": "2 tbsp sugar"}, {"name": "1 tsp baking powder", "description": "1 tsp baking powder"}, {"name": "Cooking oil", "description": "Cooking oil"}]'::jsonb, '[{"title": "Step 1", "description": "Peel and flatten each saba banana."}, {"title": "Step 2", "description": "Mix the flour, egg, milk, sugar, and baking powder until smooth."}, {"title": "Step 3", "description": "Dip each banana into the batter."}, {"title": "Step 4", "description": "Heat oil over medium heat."}, {"title": "Step 5", "description": "Fry until both sides are golden brown."}, {"title": "Step 6", "description": "Drain on paper towels."}, {"title": "Step 7", "description": "Sprinkle with sugar before serving."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Carioca', 'Snack', '30 min', 'Easy', '', '1 person', '280 kcal', NULL, '[{"name": "2 cups glutinous rice flour", "description": "2 cups glutinous rice flour"}, {"name": "1 cup grated coconut", "description": "1 cup grated coconut"}, {"name": "3/4 cup water", "description": "3/4 cup water"}, {"name": "1 cup brown sugar", "description": "1 cup brown sugar"}, {"name": "Cooking oil", "description": "Cooking oil"}]'::jsonb, '[{"title": "Step 1", "description": "Combine the glutinous rice flour, grated coconut, and water."}, {"title": "Step 2", "description": "Mix until a soft dough forms."}, {"title": "Step 3", "description": "Roll into small balls."}, {"title": "Step 4", "description": "Deep-fry until golden brown."}, {"title": "Step 5", "description": "Melt the brown sugar in a separate pan."}, {"title": "Step 6", "description": "Toss the fried balls in the caramel."}, {"title": "Step 7", "description": "Serve warm."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Puto Cheese', 'Snack', '30 min', 'Easy', '', '1 person', '180 kcal', NULL, '[{"name": "2 cups all-purpose flour", "description": "2 cups all-purpose flour"}, {"name": "1 cup sugar", "description": "1 cup sugar"}, {"name": "1 tbsp baking powder", "description": "1 tbsp baking powder"}, {"name": "1 cup fresh milk", "description": "1 cup fresh milk"}, {"name": "2 eggs", "description": "2 eggs"}, {"name": "1/4 cup melted butter", "description": "1/4 cup melted butter"}, {"name": "Cheese slices, cut into small squares", "description": "Cheese slices, cut into small squares"}]'::jsonb, '[{"title": "Step 1", "description": "Combine all dry ingredients."}, {"title": "Step 2", "description": "Add the milk, eggs, and melted butter."}, {"title": "Step 3", "description": "Mix until smooth."}, {"title": "Step 4", "description": "Fill puto molds three-fourths full."}, {"title": "Step 5", "description": "Top each with cheese."}, {"title": "Step 6", "description": "Steam for 15 minutes."}, {"title": "Step 7", "description": "Remove from molds and serve warm."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Palitaw', 'Snack', '30 min', 'Easy', '', '1 person', '220 kcal', NULL, '[{"name": "2 cups glutinous rice flour", "description": "2 cups glutinous rice flour"}, {"name": "1 cup water", "description": "1 cup water"}, {"name": "1 cup grated coconut", "description": "1 cup grated coconut"}, {"name": "1/2 cup sugar", "description": "1/2 cup sugar"}, {"name": "1/4 cup toasted sesame seeds", "description": "1/4 cup toasted sesame seeds"}]'::jsonb, '[{"title": "Step 1", "description": "Mix the rice flour and water to form a soft dough."}, {"title": "Step 2", "description": "Shape into small flat oval pieces."}, {"title": "Step 3", "description": "Boil water in a pot."}, {"title": "Step 4", "description": "Drop the dough pieces into the boiling water."}, {"title": "Step 5", "description": "Cook until they float."}, {"title": "Step 6", "description": "Remove and coat with grated coconut."}, {"title": "Step 7", "description": "Sprinkle with sugar and sesame seeds before serving."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Nilupak na Kamoteng Kahoy', 'Snack', '30 min', 'Easy', '', '1 person', '300 kcal', NULL, '[{"name": "1 kg cassava, peeled", "description": "1 kg cassava, peeled"}, {"name": "1/4 cup butter", "description": "1/4 cup butter"}, {"name": "1/2 cup condensed milk", "description": "1/2 cup condensed milk"}, {"name": "1 cup grated coconut", "description": "1 cup grated coconut"}, {"name": "1/2 tsp salt", "description": "1/2 tsp salt"}]'::jsonb, '[{"title": "Step 1", "description": "Boil the cassava until fork-tender."}, {"title": "Step 2", "description": "Drain and mash until smooth."}, {"title": "Step 3", "description": "Add the butter, condensed milk, and salt."}, {"title": "Step 4", "description": "Continue mashing until well combined."}, {"title": "Step 5", "description": "Transfer to a serving plate."}, {"title": "Step 6", "description": "Top generously with grated coconut."}, {"title": "Step 7", "description": "Serve warm or chilled."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Tupig', 'Snack', '30 min', 'Easy', '', '1 person', '250 kcal', NULL, '[{"name": "2 cups glutinous rice flour", "description": "2 cups glutinous rice flour"}, {"name": "1 cup brown sugar", "description": "1 cup brown sugar"}, {"name": "1 cup grated young coconut", "description": "1 cup grated young coconut"}, {"name": "1 cup coconut milk", "description": "1 cup coconut milk"}, {"name": "1 tsp vanilla extract", "description": "1 tsp vanilla extract"}, {"name": "Banana leaves, wilted", "description": "Banana leaves, wilted"}, {"name": "Kitchen string", "description": "Kitchen string"}]'::jsonb, '[{"title": "Step 1", "description": "In a bowl, combine the glutinous rice flour, brown sugar, grated coconut, coconut milk, and vanilla extract."}, {"title": "Step 2", "description": "Mix until a smooth batter forms."}, {"title": "Step 3", "description": "Place about 1/4 cup of the mixture onto a wilted banana leaf."}, {"title": "Step 4", "description": "Fold the banana leaf tightly and secure it with kitchen string."}, {"title": "Step 5", "description": "Preheat a grill over medium heat."}, {"title": "Step 6", "description": "Grill each tupig for 15–20 minutes, turning occasionally until lightly charred."}, {"title": "Step 7", "description": "Serve warm."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Bibingkang Malagkit', 'Snack', '30 min', 'Easy', '', '1 person', '350 kcal', NULL, '[{"name": "2 cups glutinous rice", "description": "2 cups glutinous rice"}, {"name": "2 cups coconut milk", "description": "2 cups coconut milk"}, {"name": "11/2 cups brown sugar", "description": "11/2 cups brown sugar"}, {"name": "1 cup coconut cream", "description": "1 cup coconut cream"}, {"name": "1/2 tsp salt", "description": "1/2 tsp salt"}, {"name": "Banana leaves (optional)", "description": "Banana leaves (optional)"}]'::jsonb, '[{"title": "Step 1", "description": "Cook the glutinous rice until tender."}, {"title": "Step 2", "description": "Simmer the coconut milk with half of the brown sugar."}, {"title": "Step 3", "description": "Mix the cooked rice into the coconut mixture."}, {"title": "Step 4", "description": "Transfer to a baking dish lined with banana leaves."}, {"title": "Step 5", "description": "Simmer the coconut cream with the remaining brown sugar until thick."}, {"title": "Step 6", "description": "Spread the topping over the rice mixture."}, {"title": "Step 7", "description": "Bake at 180°C (350°F) for 20–25 minutes until lightly browned."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Puto Bumbong', 'Snack', '30 min', 'Easy', '', '1 person', '300 kcal', NULL, '[{"name": "2 cups purple glutinous rice flour", "description": "2 cups purple glutinous rice flour"}, {"name": "1/2 cup water", "description": "1/2 cup water"}, {"name": "Butter", "description": "Butter"}, {"name": "1 cup grated coconut", "description": "1 cup grated coconut"}, {"name": "1/2 cup muscovado sugar", "description": "1/2 cup muscovado sugar"}]'::jsonb, '[{"title": "Step 1", "description": "Mix the rice flour with water until slightly moist."}, {"title": "Step 2", "description": "Fill puto bumbong tubes halfway with the mixture."}, {"title": "Step 3", "description": "Steam for 8–10 minutes."}, {"title": "Step 4", "description": "Remove carefully from the bamboo tubes."}, {"title": "Step 5", "description": "Brush with butter."}, {"title": "Step 6", "description": "Sprinkle generously with grated coconut and muscovado sugar."}, {"title": "Step 7", "description": "Serve warm."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Sinukmani', 'Snack', '30 min', 'Easy', '', '1 person', '350 kcal', NULL, '[{"name": "2 cups glutinous rice", "description": "2 cups glutinous rice"}, {"name": "2 cups coconut milk", "description": "2 cups coconut milk"}, {"name": "1 cup brown sugar", "description": "1 cup brown sugar"}, {"name": "1 cup coconut cream", "description": "1 cup coconut cream"}, {"name": "1/2 tsp salt", "description": "1/2 tsp salt"}]'::jsonb, '[{"title": "Step 1", "description": "Cook the glutinous rice until tender."}, {"title": "Step 2", "description": "Simmer the coconut milk, brown sugar, and salt."}, {"title": "Step 3", "description": "Add the cooked rice and stir until thick."}, {"title": "Step 4", "description": "Transfer to a serving tray."}, {"title": "Step 5", "description": "Cook the coconut cream until latik forms."}, {"title": "Step 6", "description": "Sprinkle the latik over the rice cake."}, {"title": "Step 7", "description": "Cool slightly before serving."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Ginataang Mais', 'Snack', '30 min', 'Easy', '', '1 person', '320 kcal', NULL, '[{"name": "2 cups sweet corn kernels", "description": "2 cups sweet corn kernels"}, {"name": "1/2 cup glutinous rice", "description": "1/2 cup glutinous rice"}, {"name": "2 cups coconut milk", "description": "2 cups coconut milk"}, {"name": "1 cup coconut cream", "description": "1 cup coconut cream"}, {"name": "1/2 cup sugar", "description": "1/2 cup sugar"}, {"name": "1/4 tsp salt", "description": "1/4 tsp salt"}]'::jsonb, '[{"title": "Step 1", "description": "Wash the glutinous rice thoroughly."}, {"title": "Step 2", "description": "Bring the coconut milk to a gentle boil."}, {"title": "Step 3", "description": "Add the glutinous rice and cook until almost tender."}, {"title": "Step 4", "description": "Stir in the sweet corn."}, {"title": "Step 5", "description": "Add the sugar and salt."}, {"title": "Step 6", "description": "Pour in the coconut cream and simmer for 5 minutes."}, {"title": "Step 7", "description": "Serve warm."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Nilagang Mani', 'Snack', '30 min', 'Easy', '', '1 person', '250 kcal', NULL, '[{"name": "1 kg fresh peanuts (with shells)", "description": "1 kg fresh peanuts (with shells)"}, {"name": "3 liters water", "description": "3 liters water"}, {"name": "1/4 cup rock salt", "description": "1/4 cup rock salt"}]'::jsonb, '[{"title": "Step 1", "description": "Wash the peanuts thoroughly."}, {"title": "Step 2", "description": "Place them in a large pot."}, {"title": "Step 3", "description": "Add the water and rock salt."}, {"title": "Step 4", "description": "Bring to a boil."}, {"title": "Step 5", "description": "Simmer for 11/2–2 hours until the peanuts are tender."}, {"title": "Step 6", "description": "Drain well."}, {"title": "Step 7", "description": "Serve warm."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Kalamay Hati', 'Snack', '30 min', 'Easy', '', '1 person', '350 kcal', NULL, '[{"name": "2 cups glutinous rice flour", "description": "2 cups glutinous rice flour"}, {"name": "2 cups coconut milk", "description": "2 cups coconut milk"}, {"name": "11/2 cups muscovado sugar", "description": "11/2 cups muscovado sugar"}, {"name": "1/2 cup coconut cream", "description": "1/2 cup coconut cream"}, {"name": "1/2 tsp salt", "description": "1/2 tsp salt"}]'::jsonb, '[{"title": "Step 1", "description": "Combine the coconut milk and muscovado sugar in a saucepan."}, {"title": "Step 2", "description": "Bring to a gentle simmer."}, {"title": "Step 3", "description": "Gradually stir in the glutinous rice flour."}, {"title": "Step 4", "description": "Continue stirring until very thick."}, {"title": "Step 5", "description": "Add the coconut cream."}, {"title": "Step 6", "description": "Transfer to a greased tray."}, {"title": "Step 7", "description": "Cool completely before slicing."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Minatamis na Saging', 'Snack', '30 min', 'Easy', '', '1 person', '250 kcal', NULL, '[{"name": "6 ripe saba bananas", "description": "6 ripe saba bananas"}, {"name": "1 cup brown sugar", "description": "1 cup brown sugar"}, {"name": "2 cups water", "description": "2 cups water"}, {"name": "1 pandan leaf (optional)", "description": "1 pandan leaf (optional)"}, {"name": "1/2 tsp vanilla extract (optional)", "description": "1/2 tsp vanilla extract (optional)"}]'::jsonb, '[{"title": "Step 1", "description": "Peel the saba bananas and cut them in half if large."}, {"title": "Step 2", "description": "Combine the water, brown sugar, and pandan leaf in a saucepan."}, {"title": "Step 3", "description": "Bring the mixture to a boil until the sugar dissolves."}, {"title": "Step 4", "description": "Add the saba bananas to the syrup."}, {"title": "Step 5", "description": "Simmer over low heat for 15–20 minutes until the bananas are tender."}, {"title": "Step 6", "description": "Remove the pandan leaf and stir in the vanilla extract, if using."}, {"title": "Step 7", "description": "Serve warm on its own or with crushed ice and evaporated milk."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Cheese Sticks', 'Snack', '30 min', 'Easy', '', '1 person', '350 kcal', NULL, '[{"name": "250g quick-melt cheese, cut into sticks", "description": "250g quick-melt cheese, cut into sticks"}, {"name": "20 lumpia wrappers", "description": "20 lumpia wrappers"}, {"name": "Water for sealing", "description": "Water for sealing"}, {"name": "Cooking oil for frying", "description": "Cooking oil for frying"}]'::jsonb, '[{"title": "Step 1", "description": "Place one cheese stick on a lumpia wrapper."}, {"title": "Step 2", "description": "Roll tightly and fold the sides inward."}, {"title": "Step 3", "description": "Seal the edge with water."}, {"title": "Step 4", "description": "Heat oil over medium heat."}, {"title": "Step 5", "description": "Fry until golden brown and crispy."}, {"title": "Step 6", "description": "Remove and drain excess oil."}, {"title": "Step 7", "description": "Serve with ketchup or mayonnaise."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Pritong Kamote', 'Snack', '30 min', 'Easy', '', '1 person', '300 kcal', NULL, '[{"name": "500g sweet potatoes", "description": "500g sweet potatoes"}, {"name": "3 cups cooking oil", "description": "3 cups cooking oil"}, {"name": "1/2 tsp salt", "description": "1/2 tsp salt"}]'::jsonb, '[{"title": "Step 1", "description": "Peel and slice the sweet potatoes into thin rounds."}, {"title": "Step 2", "description": "Pat the slices dry using paper towels."}, {"title": "Step 3", "description": "Heat oil over medium-high heat."}, {"title": "Step 4", "description": "Fry the slices until golden brown and crispy."}, {"title": "Step 5", "description": "Stir occasionally for even cooking."}, {"title": "Step 6", "description": "Drain excess oil."}, {"title": "Step 7", "description": "Sprinkle with salt and serve warm."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Binangkal', 'Snack', '30 min', 'Easy', '', '1 person', '320 kcal', NULL, '[{"name": "2 cups all-purpose flour", "description": "2 cups all-purpose flour"}, {"name": "1/2 cup sugar", "description": "1/2 cup sugar"}, {"name": "1 tsp baking powder", "description": "1 tsp baking powder"}, {"name": "1 egg", "description": "1 egg"}, {"name": "1/4 cup milk", "description": "1/4 cup milk"}, {"name": "2 tbsp butter, melted", "description": "2 tbsp butter, melted"}, {"name": "1/2 cup sesame seeds", "description": "1/2 cup sesame seeds"}, {"name": "Cooking oil for frying", "description": "Cooking oil for frying"}]'::jsonb, '[{"title": "Step 1", "description": "Mix the flour, sugar, and baking powder."}, {"title": "Step 2", "description": "Add the egg, milk, and butter."}, {"title": "Step 3", "description": "Knead into a smooth dough."}, {"title": "Step 4", "description": "Shape into small balls."}, {"title": "Step 5", "description": "Roll each ball in sesame seeds."}, {"title": "Step 6", "description": "Fry until golden brown."}, {"title": "Step 7", "description": "Drain and serve warm."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Buchi', 'Snack', '30 min', 'Easy', '', '1 person', '300 kcal', NULL, '[{"name": "2 cups glutinous rice flour", "description": "2 cups glutinous rice flour"}, {"name": "3/4 cup warm water", "description": "3/4 cup warm water"}, {"name": "1 cup sweet mung bean paste", "description": "1 cup sweet mung bean paste"}, {"name": "1 cup sesame seeds", "description": "1 cup sesame seeds"}, {"name": "Cooking oil for frying", "description": "Cooking oil for frying"}]'::jsonb, '[{"title": "Step 1", "description": "Mix the glutinous rice flour and water to form a dough."}, {"title": "Step 2", "description": "Divide into equal portions."}, {"title": "Step 3", "description": "Flatten each portion and place mung bean paste in the center."}, {"title": "Step 4", "description": "Seal and roll into balls."}, {"title": "Step 5", "description": "Coat each ball with sesame seeds."}, {"title": "Step 6", "description": "Fry over low heat until golden and puffed."}, {"title": "Step 7", "description": "Drain and serve warm."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Empanadang Gulay', 'Snack', '30 min', 'Easy', '', '1 person', '280 kcal', NULL, '[{"name": "10 empanada dough wrappers", "description": "10 empanada dough wrappers"}, {"name": "1 cup cabbage, shredded", "description": "1 cup cabbage, shredded"}, {"name": "1/2 cup carrots, diced", "description": "1/2 cup carrots, diced"}, {"name": "1/2 cup potatoes, diced", "description": "1/2 cup potatoes, diced"}, {"name": "1/4 cup green peas", "description": "1/4 cup green peas"}, {"name": "1 onion, chopped", "description": "1 onion, chopped"}, {"name": "3 cloves garlic, minced", "description": "3 cloves garlic, minced"}, {"name": "2 tbsp cooking oil", "description": "2 tbsp cooking oil"}, {"name": "Salt and pepper to taste", "description": "Salt and pepper to taste"}, {"name": "Oil for frying (optional)", "description": "Oil for frying (optional)"}]'::jsonb, '[{"title": "Step 1", "description": "Heat oil and sauté the garlic and onion until fragrant."}, {"title": "Step 2", "description": "Add the potatoes and carrots; cook until tender."}, {"title": "Step 3", "description": "Stir in the cabbage and green peas. Season with salt and pepper."}, {"title": "Step 4", "description": "Allow the filling to cool completely."}, {"title": "Step 5", "description": "Place the filling on each empanada wrapper and fold into a half-moon shape. Seal the edges with a fork."}, {"title": "Step 6", "description": "Bake at 190°C (375°F) for 25–30 minutes, or deep-fry until golden brown."}, {"title": "Step 7", "description": "Serve warm with banana ketchup or vinegar."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Nilupak na Saging', 'Snack', '30 min', 'Easy', '', '1 person', '350 kcal', NULL, '[{"name": "8 ripe saba bananas", "description": "8 ripe saba bananas"}, {"name": "1/4 cup butter", "description": "1/4 cup butter"}, {"name": "1/2 cup condensed milk", "description": "1/2 cup condensed milk"}, {"name": "1 cup freshly grated coconut", "description": "1 cup freshly grated coconut"}, {"name": "1/4 tsp salt", "description": "1/4 tsp salt"}]'::jsonb, '[{"title": "Step 1", "description": "Boil the saba bananas until tender, about 15–20 minutes."}, {"title": "Step 2", "description": "Peel the bananas while still warm."}, {"title": "Step 3", "description": "Mash the bananas until smooth using a mortar and pestle or potato masher."}, {"title": "Step 4", "description": "Add the butter, condensed milk, and salt."}, {"title": "Step 5", "description": "Continue mashing until well combined."}, {"title": "Step 6", "description": "Transfer to a serving plate and top with grated coconut."}, {"title": "Step 7", "description": "Serve warm."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Puto Flan', 'Snack', '30 min', 'Easy', '', '1 person', '250 kcal', NULL, '[{"name": "2 cups puto batter", "description": "2 cups puto batter"}, {"name": "1 prepared leche flan", "description": "1 prepared leche flan"}, {"name": "Butter for greasing molds", "description": "Butter for greasing molds"}]'::jsonb, '[{"title": "Step 1", "description": "Grease the puto molds with butter."}, {"title": "Step 2", "description": "Fill each mold halfway with puto batter."}, {"title": "Step 3", "description": "Steam for 8 minutes."}, {"title": "Step 4", "description": "Cut the leche flan into small circles or squares."}, {"title": "Step 5", "description": "Place a piece of leche flan on each partially cooked puto."}, {"title": "Step 6", "description": "Steam for another 7–8 minutes."}, {"title": "Step 7", "description": "Cool slightly before serving."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Puto Maya', 'Snack', '30 min', 'Easy', '', '1 person', '300 kcal', NULL, '[{"name": "2 cups glutinous rice", "description": "2 cups glutinous rice"}, {"name": "2 cups coconut milk", "description": "2 cups coconut milk"}, {"name": "1 thumb-sized ginger, sliced", "description": "1 thumb-sized ginger, sliced"}, {"name": "1/2 tsp salt", "description": "1/2 tsp salt"}, {"name": "Banana leaves for lining", "description": "Banana leaves for lining"}]'::jsonb, '[{"title": "Step 1", "description": "Wash the glutinous rice thoroughly."}, {"title": "Step 2", "description": "Combine the coconut milk, ginger, and salt in a pot."}, {"title": "Step 3", "description": "Add the rice and cook over low heat."}, {"title": "Step 4", "description": "Stir occasionally until the liquid is absorbed."}, {"title": "Step 5", "description": "Transfer to banana leaf-lined molds."}, {"title": "Step 6", "description": "Steam for 20 minutes."}, {"title": "Step 7", "description": "Serve warm with ripe mangoes."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Kalamay sa Latik', 'Snack', '30 min', 'Easy', '', '1 person', '350 kcal', NULL, '[{"name": "2 cups glutinous rice flour", "description": "2 cups glutinous rice flour"}, {"name": "2 cups coconut milk", "description": "2 cups coconut milk"}, {"name": "1 cup brown sugar", "description": "1 cup brown sugar"}, {"name": "1 cup coconut cream", "description": "1 cup coconut cream"}, {"name": "1/2 tsp salt", "description": "1/2 tsp salt"}]'::jsonb, '[{"title": "Step 1", "description": "Heat the coconut milk in a saucepan."}, {"title": "Step 2", "description": "Add the brown sugar and salt."}, {"title": "Step 3", "description": "Gradually stir in the glutinous rice flour."}, {"title": "Step 4", "description": "Cook until thick while stirring continuously."}, {"title": "Step 5", "description": "Pour into a greased tray."}, {"title": "Step 6", "description": "Cook the coconut cream until latik forms."}, {"title": "Step 7", "description": "Sprinkle the latik on top before serving."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Sinapot', 'Snack', '30 min', 'Easy', '', '1 person', '180 kcal', NULL, '[{"name": "8 ripe saba bananas", "description": "8 ripe saba bananas"}, {"name": "Water for steaming", "description": "Water for steaming"}]'::jsonb, '[{"title": "Step 1", "description": "Wash the saba bananas thoroughly."}, {"title": "Step 2", "description": "Arrange them in a steamer basket."}, {"title": "Step 3", "description": "Steam over boiling water for 20–25 minutes."}, {"title": "Step 4", "description": "Check that the bananas are soft."}, {"title": "Step 5", "description": "Remove from the steamer."}, {"title": "Step 6", "description": "Peel while still warm."}, {"title": "Step 7", "description": "Serve as is or with grated coconut."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Adobong Mani', 'Snack', '30 min', 'Easy', '', '1 person', '300 kcal', NULL, '[{"name": "500g raw peanuts", "description": "500g raw peanuts"}, {"name": "6 cloves garlic, sliced", "description": "6 cloves garlic, sliced"}, {"name": "3 cups cooking oil", "description": "3 cups cooking oil"}, {"name": "1 tsp salt", "description": "1 tsp salt"}]'::jsonb, '[{"title": "Step 1", "description": "Heat the oil over low heat."}, {"title": "Step 2", "description": "Fry the garlic until golden and remove."}, {"title": "Step 3", "description": "Add the peanuts and fry slowly until cooked."}, {"title": "Step 4", "description": "Remove and drain well."}, {"title": "Step 5", "description": "Toss with salt."}, {"title": "Step 6", "description": "Mix in the fried garlic."}, {"title": "Step 7", "description": "Cool completely before serving."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Pastillas de Leche', 'Snack', '30 min', 'Easy', '', '1 person', '220 kcal', NULL, '[{"name": "2 cups powdered milk", "description": "2 cups powdered milk"}, {"name": "1 can (300ml) condensed milk", "description": "1 can (300ml) condensed milk"}, {"name": "1/2 cup white sugar", "description": "1/2 cup white sugar"}]'::jsonb, '[{"title": "Step 1", "description": "Combine the powdered milk and condensed milk."}, {"title": "Step 2", "description": "Mix until a soft dough forms."}, {"title": "Step 3", "description": "Scoop small portions and roll into logs."}, {"title": "Step 4", "description": "Roll each piece in sugar."}, {"title": "Step 5", "description": "Arrange on a tray."}, {"title": "Step 6", "description": "Chill for 30 minutes."}, {"title": "Step 7", "description": "Wrap individually and serve."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Yema Balls', 'Snack', '30 min', 'Easy', '', '1 person', '250 kcal', NULL, '[{"name": "1 can condensed milk", "description": "1 can condensed milk"}, {"name": "4 egg yolks", "description": "4 egg yolks"}, {"name": "2 tbsp butter", "description": "2 tbsp butter"}, {"name": "1/2 cup white sugar", "description": "1/2 cup white sugar"}]'::jsonb, '[{"title": "Step 1", "description": "Combine the condensed milk and egg yolks in a saucepan."}, {"title": "Step 2", "description": "Cook over low heat while stirring continuously."}, {"title": "Step 3", "description": "Add the butter and continue cooking until thick."}, {"title": "Step 4", "description": "Allow the mixture to cool completely."}, {"title": "Step 5", "description": "Scoop small portions and roll into balls."}, {"title": "Step 6", "description": "Coat each ball with sugar."}, {"title": "Step 7", "description": "Refrigerate before serving."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Ginanggang', 'Snack', '30 min', 'Easy', '', '1 person', '250 kcal', NULL, '[{"name": "6 semi-ripe saba bananas", "description": "6 semi-ripe saba bananas"}, {"name": "1/4 cup margarine, melted", "description": "1/4 cup margarine, melted"}, {"name": "1/4 cup white sugar", "description": "1/4 cup white sugar"}, {"name": "Bamboo skewers", "description": "Bamboo skewers"}]'::jsonb, '[{"title": "Step 1", "description": "Peel the saba bananas and insert each onto a bamboo skewer."}, {"title": "Step 2", "description": "Preheat a charcoal grill over medium heat."}, {"title": "Step 3", "description": "Grill the bananas for 5–7 minutes, turning occasionally."}, {"title": "Step 4", "description": "Brush each banana generously with melted margarine."}, {"title": "Step 5", "description": "Continue grilling until lightly caramelized."}, {"title": "Step 6", "description": "Sprinkle with sugar while still hot."}, {"title": "Step 7", "description": "Serve immediately."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Nilasing na Saging', 'Snack', '30 min', 'Easy', '', '1 person', '300 kcal', NULL, '[{"name": "6 ripe saba bananas", "description": "6 ripe saba bananas"}, {"name": "1 cup all-purpose flour", "description": "1 cup all-purpose flour"}, {"name": "1 egg", "description": "1 egg"}, {"name": "1/2 cup fresh milk", "description": "1/2 cup fresh milk"}, {"name": "2 tbsp sugar", "description": "2 tbsp sugar"}, {"name": "1/2 tsp vanilla extract", "description": "1/2 tsp vanilla extract"}, {"name": "1/2 tsp ground cinnamon", "description": "1/2 tsp ground cinnamon"}, {"name": "Cooking oil for frying", "description": "Cooking oil for frying"}]'::jsonb, '[{"title": "Step 1", "description": "Peel the saba bananas and cut them in half lengthwise."}, {"title": "Step 2", "description": "In a bowl, combine the flour, egg, milk, sugar, vanilla, and cinnamon."}, {"title": "Step 3", "description": "Mix until smooth."}, {"title": "Step 4", "description": "Dip each banana into the batter."}, {"title": "Step 5", "description": "Fry in hot oil until golden brown."}, {"title": "Step 6", "description": "Drain on paper towels."}, {"title": "Step 7", "description": "Serve warm."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Pritong Mais', 'Snack', '30 min', 'Easy', '', '1 person', '280 kcal', NULL, '[{"name": "2 cups fresh corn kernels", "description": "2 cups fresh corn kernels"}, {"name": "1 cup all-purpose flour", "description": "1 cup all-purpose flour"}, {"name": "1/4 cup cornstarch", "description": "1/4 cup cornstarch"}, {"name": "1 egg", "description": "1 egg"}, {"name": "3/4 cup water", "description": "3/4 cup water"}, {"name": "1/2 tsp salt", "description": "1/2 tsp salt"}, {"name": "1/2 tsp pepper", "description": "1/2 tsp pepper"}, {"name": "Cooking oil for frying", "description": "Cooking oil for frying"}]'::jsonb, '[{"title": "Step 1", "description": "Mix the flour, cornstarch, egg, water, salt, and pepper."}, {"title": "Step 2", "description": "Fold in the corn kernels."}, {"title": "Step 3", "description": "Heat oil over medium heat."}, {"title": "Step 4", "description": "Scoop spoonfuls of the batter into the hot oil."}, {"title": "Step 5", "description": "Fry until golden brown and crispy."}, {"title": "Step 6", "description": "Drain excess oil."}, {"title": "Step 7", "description": "Serve warm."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Kamote Balls', 'Snack', '30 min', 'Easy', '', '1 person', '300 kcal', NULL, '[{"name": "500g sweet potatoes", "description": "500g sweet potatoes"}, {"name": "1 cup all-purpose flour", "description": "1 cup all-purpose flour"}, {"name": "1/4 cup sugar", "description": "1/4 cup sugar"}, {"name": "1 egg", "description": "1 egg"}, {"name": "1/2 tsp baking powder", "description": "1/2 tsp baking powder"}, {"name": "Cooking oil for frying", "description": "Cooking oil for frying"}]'::jsonb, '[{"title": "Step 1", "description": "Boil the sweet potatoes until tender."}, {"title": "Step 2", "description": "Mash until smooth."}, {"title": "Step 3", "description": "Add the flour, sugar, egg, and baking powder."}, {"title": "Step 4", "description": "Mix until a soft dough forms."}, {"title": "Step 5", "description": "Shape into small balls."}, {"title": "Step 6", "description": "Fry until golden brown."}, {"title": "Step 7", "description": "Drain and serve warm."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Puto Pandan', 'Snack', '30 min', 'Easy', '', '1 person', '180 kcal', NULL, '[{"name": "2 cups all-purpose flour", "description": "2 cups all-purpose flour"}, {"name": "1 cup sugar", "description": "1 cup sugar"}, {"name": "1 tbsp baking powder", "description": "1 tbsp baking powder"}, {"name": "1 cup pandan juice", "description": "1 cup pandan juice"}, {"name": "2 eggs", "description": "2 eggs"}, {"name": "1/4 cup melted butter", "description": "1/4 cup melted butter"}, {"name": "Cheese cubes for topping", "description": "Cheese cubes for topping"}]'::jsonb, '[{"title": "Step 1", "description": "Combine the flour, sugar, and baking powder."}, {"title": "Step 2", "description": "Add the pandan juice, eggs, and butter."}, {"title": "Step 3", "description": "Mix until smooth."}, {"title": "Step 4", "description": "Fill greased puto molds three-fourths full."}, {"title": "Step 5", "description": "Place a cheese cube on top."}, {"title": "Step 6", "description": "Steam for 15 minutes."}, {"title": "Step 7", "description": "Remove from the molds and serve warm."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Ube Halaya', 'Snack', '30 min', 'Easy', '', '1 person', '300 kcal', NULL, '[{"name": "1 kg purple yam (ube), boiled and grated", "description": "1 kg purple yam (ube), boiled and grated"}, {"name": "1 can condensed milk", "description": "1 can condensed milk"}, {"name": "1 can evaporated milk", "description": "1 can evaporated milk"}, {"name": "1/2 cup butter", "description": "1/2 cup butter"}, {"name": "1/2 cup sugar", "description": "1/2 cup sugar"}]'::jsonb, '[{"title": "Step 1", "description": "Combine the grated ube, condensed milk, evaporated milk, and sugar in a pan."}, {"title": "Step 2", "description": "Cook over low heat while stirring continuously."}, {"title": "Step 3", "description": "Add the butter gradually."}, {"title": "Step 4", "description": "Continue cooking until thick and smooth."}, {"title": "Step 5", "description": "Transfer to a greased serving dish."}, {"title": "Step 6", "description": "Brush the top with butter."}, {"title": "Step 7", "description": "Cool before serving."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Puto Calasiao', 'Snack', '30 min', 'Easy', '', '1 person', '220 kcal', NULL, '[{"name": "2 cups rice flour", "description": "2 cups rice flour"}, {"name": "3/4 cup sugar", "description": "3/4 cup sugar"}, {"name": "1 cup water", "description": "1 cup water"}, {"name": "1 tsp yeast", "description": "1 tsp yeast"}, {"name": "1/4 tsp salt", "description": "1/4 tsp salt"}]'::jsonb, '[{"title": "Step 1", "description": "Dissolve the yeast in warm water."}, {"title": "Step 2", "description": "Combine the rice flour, sugar, and salt."}, {"title": "Step 3", "description": "Add the yeast mixture and mix thoroughly."}, {"title": "Step 4", "description": "Let the batter ferment for 2–3 hours."}, {"title": "Step 5", "description": "Pour into small molds."}, {"title": "Step 6", "description": "Steam for 15–20 minutes."}, {"title": "Step 7", "description": "Cool slightly before serving."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Bibingkang Galapong', 'Snack', '30 min', 'Easy', '', '1 person', '300 kcal', NULL, '[{"name": "2 cups galapong (ground soaked rice)", "description": "2 cups galapong (ground soaked rice)"}, {"name": "1 cup coconut milk", "description": "1 cup coconut milk"}, {"name": "1/2 cup sugar", "description": "1/2 cup sugar"}, {"name": "2 eggs", "description": "2 eggs"}, {"name": "1 tsp baking powder", "description": "1 tsp baking powder"}, {"name": "2 salted eggs, sliced", "description": "2 salted eggs, sliced"}, {"name": "1/2 cup grated coconut", "description": "1/2 cup grated coconut"}, {"name": "Butter for brushing", "description": "Butter for brushing"}]'::jsonb, '[{"title": "Step 1", "description": "Preheat the oven to 180°C (350°F)."}, {"title": "Step 2", "description": "Mix the galapong, coconut milk, sugar, eggs, and baking powder until smooth."}, {"title": "Step 3", "description": "Pour the batter into a greased baking pan lined with banana leaves, if available."}, {"title": "Step 4", "description": "Arrange the sliced salted eggs on top."}, {"title": "Step 5", "description": "Bake for 25–30 minutes or until lightly golden."}, {"title": "Step 6", "description": "Brush with butter and sprinkle with grated coconut."}, {"title": "Step 7", "description": "Serve warm."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Ube Leche Flan Cake', 'Snack', '30 min', 'Easy', '', '1 person', '450 kcal', NULL, '[{"name": "1 prepared ube cake batter", "description": "1 prepared ube cake batter"}, {"name": "1 prepared leche flan", "description": "1 prepared leche flan"}, {"name": "2 eggs", "description": "2 eggs"}, {"name": "1/2 cup evaporated milk", "description": "1/2 cup evaporated milk"}, {"name": "Butter for greasing the pan", "description": "Butter for greasing the pan"}]'::jsonb, '[{"title": "Step 1", "description": "Preheat the oven to 175°C (350°F)."}, {"title": "Step 2", "description": "Grease a round cake pan with butter."}, {"title": "Step 3", "description": "Pour the ube cake batter into the pan."}, {"title": "Step 4", "description": "Carefully place the prepared leche flan on top of the batter."}, {"title": "Step 5", "description": "Bake for 45–50 minutes or until a toothpick inserted into the cake comes out clean."}, {"title": "Step 6", "description": "Cool completely before inverting onto a serving plate."}, {"title": "Step 7", "description": "Slice and serve chilled or at room temperature."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Mango Sago', 'Snack', '30 min', 'Easy', '', '1 person', '350 kcal', NULL, '[{"name": "2 ripe mangoes, diced", "description": "2 ripe mangoes, diced"}, {"name": "1 cup cooked small sago pearls", "description": "1 cup cooked small sago pearls"}, {"name": "1 cup all-purpose cream", "description": "1 cup all-purpose cream"}, {"name": "1/2 cup condensed milk", "description": "1/2 cup condensed milk"}, {"name": "1/2 cup evaporated milk", "description": "1/2 cup evaporated milk"}]'::jsonb, '[{"title": "Step 1", "description": "Cook the sago pearls according to the package instructions and drain."}, {"title": "Step 2", "description": "Combine the all-purpose cream, condensed milk, and evaporated milk."}, {"title": "Step 3", "description": "Add the cooked sago pearls and diced mangoes."}, {"title": "Step 4", "description": "Fold gently until well combined."}, {"title": "Step 5", "description": "Transfer to a serving bowl."}, {"title": "Step 6", "description": "Refrigerate for at least 2 hours."}, {"title": "Step 7", "description": "Serve chilled."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Pineapple Macapuno Delight', 'Snack', '30 min', 'Easy', '', '1 person', '380 kcal', NULL, '[{"name": "2 cups pineapple chunks, drained", "description": "2 cups pineapple chunks, drained"}, {"name": "1 cup macapuno strings", "description": "1 cup macapuno strings"}, {"name": "1 cup all-purpose cream", "description": "1 cup all-purpose cream"}, {"name": "1 can condensed milk", "description": "1 can condensed milk"}, {"name": "1/2 cup nata de coco", "description": "1/2 cup nata de coco"}]'::jsonb, '[{"title": "Step 1", "description": "Drain the pineapple chunks thoroughly."}, {"title": "Step 2", "description": "Combine the pineapple, macapuno, and nata de coco in a bowl."}, {"title": "Step 3", "description": "Mix the all-purpose cream and condensed milk."}, {"title": "Step 4", "description": "Pour the cream mixture over the fruit."}, {"title": "Step 5", "description": "Fold gently until well combined."}, {"title": "Step 6", "description": "Chill for at least 3 hours."}, {"title": "Step 7", "description": "Serve cold."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Langka Ice Cream', 'Snack', '30 min', 'Easy', '', '1 person', '350 kcal', NULL, '[{"name": "2 cups ripe jackfruit, finely chopped", "description": "2 cups ripe jackfruit, finely chopped"}, {"name": "2 cups all-purpose cream", "description": "2 cups all-purpose cream"}, {"name": "1 can condensed milk", "description": "1 can condensed milk"}, {"name": "1 tsp vanilla extract", "description": "1 tsp vanilla extract"}]'::jsonb, '[{"title": "Step 1", "description": "Blend half of the jackfruit until smooth."}, {"title": "Step 2", "description": "Combine the blended jackfruit, chopped jackfruit, cream, condensed milk, and vanilla."}, {"title": "Step 3", "description": "Mix until well combined."}, {"title": "Step 4", "description": "Transfer to a freezer-safe container."}, {"title": "Step 5", "description": "Cover tightly."}, {"title": "Step 6", "description": "Freeze overnight."}, {"title": "Step 7", "description": "Scoop and serve."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Sweet Potato Halaya', 'Snack', '30 min', 'Easy', '', '1 person', '330 kcal', NULL, '[{"name": "1 kg sweet potatoes, boiled and mashed", "description": "1 kg sweet potatoes, boiled and mashed"}, {"name": "1 can condensed milk", "description": "1 can condensed milk"}, {"name": "1 cup coconut milk", "description": "1 cup coconut milk"}, {"name": "1/4 cup butter", "description": "1/4 cup butter"}, {"name": "1/2 cup sugar", "description": "1/2 cup sugar"}]'::jsonb, '[{"title": "Step 1", "description": "Combine the mashed sweet potatoes and coconut milk in a pan."}, {"title": "Step 2", "description": "Add the condensed milk and sugar."}, {"title": "Step 3", "description": "Cook over low heat while stirring continuously."}, {"title": "Step 4", "description": "Add the butter and continue stirring until thick."}, {"title": "Step 5", "description": "Transfer to a greased serving dish."}, {"title": "Step 6", "description": "Smooth the top with a spatula."}, {"title": "Step 7", "description": "Cool before serving."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Pandan Jelly Delight', 'Snack', '30 min', 'Easy', '', '1 person', '250 kcal', NULL, '[{"name": "1 pack pandan-flavored gelatin", "description": "1 pack pandan-flavored gelatin"}, {"name": "2 cups water", "description": "2 cups water"}, {"name": "1 cup all-purpose cream", "description": "1 cup all-purpose cream"}, {"name": "1/2 cup condensed milk", "description": "1/2 cup condensed milk"}, {"name": "1 cup nata de coco", "description": "1 cup nata de coco"}]'::jsonb, '[{"title": "Step 1", "description": "Prepare the pandan gelatin according to the package directions."}, {"title": "Step 2", "description": "Allow it to cool and set completely."}, {"title": "Step 3", "description": "Cut the jelly into cubes."}, {"title": "Step 4", "description": "Combine the cream and condensed milk."}, {"title": "Step 5", "description": "Fold in the jelly cubes and nata de coco."}, {"title": "Step 6", "description": "Chill for at least 2 hours."}, {"title": "Step 7", "description": "Serve cold."}]'::jsonb);

INSERT INTO public.recipes (title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps)
VALUES ('Caramel Banana Delight', 'Snack', '30 min', 'Easy', '', '1 person', '350 kcal', NULL, '[{"name": "6 ripe saba bananas", "description": "6 ripe saba bananas"}, {"name": "1/2 cup brown sugar", "description": "1/2 cup brown sugar"}, {"name": "2 tbsp butter", "description": "2 tbsp butter"}, {"name": "1 cup whipped cream", "description": "1 cup whipped cream"}, {"name": "1 cup crushed graham crackers", "description": "1 cup crushed graham crackers"}]'::jsonb, '[{"title": "Step 1", "description": "Slice the saba bananas into rounds."}, {"title": "Step 2", "description": "Melt the butter in a pan and add the brown sugar."}, {"title": "Step 3", "description": "Cook until the sugar caramelizes."}, {"title": "Step 4", "description": "Add the bananas and cook for 3–5 minutes."}, {"title": "Step 5", "description": "Allow the bananas to cool slightly."}, {"title": "Step 6", "description": "Layer the caramelized bananas, whipped cream, and crushed graham crackers in serving glasses."}, {"title": "Step 7", "description": "Chill for 1 hour before serving."}]'::jsonb);
