-- Fill gaps 113-160 (Pinaupong Manok 112 -> Tortang Talong 161)
-- Generated from FILIPINO_DESSERT_FINAL.md + FILIPINO_SNACKS_FINAL.md
-- Uses OVERRIDING SYSTEM VALUE because id is GENERATED ALWAYS AS IDENTITY

INSERT INTO public.recipes (id, title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps) OVERRIDING SYSTEM VALUE
VALUES (113, 'Sapin-Sapin', 'Dessert', '30 min', 'Medium', '', '1 person', '650 kcal', NULL, '[{"name": "1/2 cups glutinous rice flour", "description": "1/2 cups glutinous rice flour"}, {"name": "1/2 cups coconut milk", "description": "1/2 cups coconut milk"}, {"name": "1/4 cup sugar", "description": "1/4 cup sugar"}, {"name": "1/4 cup condensed milk", "description": "1/4 cup condensed milk"}, {"name": "Purple yam flavoring or ube halaya", "description": "Purple yam flavoring or ube halaya"}, {"name": "Jackfruit flavoring (optional)", "description": "Jackfruit flavoring (optional)"}, {"name": "Yellow food coloring (optional)", "description": "Yellow food coloring (optional)"}, {"name": "Latik for topping", "description": "Latik for topping"}, {"name": "Glutinous Rice Flour → rice flour + a little cornstarch", "description": "Glutinous Rice Flour → rice flour + a little cornstarch"}, {"name": "Coconut Milk → evaporated milk or fresh milk", "description": "Coconut Milk → evaporated milk or fresh milk"}, {"name": "Condensed Milk → evaporated milk + sugar", "description": "Condensed Milk → evaporated milk + sugar"}, {"name": "Ube Halaya → mashed purple sweet potato + sugar", "description": "Ube Halaya → mashed purple sweet potato + sugar"}]'::jsonb, '[{"title": "Step 1", "description": "Combine the glutinous rice flour, coconut milk, sugar, and condensed milk until smooth."}, {"title": "Step 2", "description": "Divide the batter into three portions."}, {"title": "Step 3", "description": "Color and flavor each portion differently."}, {"title": "Step 4", "description": "Pour the first layer into a greased pan and steam for 10 minutes."}, {"title": "Step 5", "description": "Add the second layer and steam for another 10 minutes."}, {"title": "Step 6", "description": "Repeat with the final layer and steam until fully cooked."}, {"title": "Step 7", "description": "Cool completely and top with latik before serving."}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.recipes (id, title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps) OVERRIDING SYSTEM VALUE
VALUES (114, 'Tibok-Tibok', 'Dessert', '30 min', 'Easy', '', '1 person', '300 kcal', NULL, '[{"name": "1 cups fresh carabao''''s milk (or whole milk)", "description": "1 cups fresh carabao''''s milk (or whole milk)"}, {"name": "1/8 cup sugar", "description": "1/8 cup sugar"}, {"name": "1/8 cup cornstarch", "description": "1/8 cup cornstarch"}, {"name": "1/8 cup water", "description": "1/8 cup water"}, {"name": "1/8 cup latik", "description": "1/8 cup latik"}, {"name": "Carabao''''S Milk → whole milk", "description": "Carabao''''S Milk → whole milk"}, {"name": "Cornstarch → all-purpose flour", "description": "Cornstarch → all-purpose flour"}, {"name": "Latik → toasted grated coconut", "description": "Latik → toasted grated coconut"}]'::jsonb, '[{"title": "Step 1", "description": "Heat the milk and sugar in a saucepan until warm."}, {"title": "Step 2", "description": "Dissolve the cornstarch in water."}, {"title": "Step 3", "description": "Slowly pour the cornstarch mixture into the milk while stirring."}, {"title": "Step 4", "description": "Continue stirring until thick and smooth."}, {"title": "Step 5", "description": "Pour into a serving dish."}, {"title": "Step 6", "description": "Let it cool completely."}, {"title": "Step 7", "description": "Top with latik before serving."}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.recipes (id, title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps) OVERRIDING SYSTEM VALUE
VALUES (115, 'Kalamay Lansong', 'Dessert', '30 min', 'Medium', '', '1 person', '500 kcal', NULL, '[{"name": "1/2 cups glutinous rice flour", "description": "1/2 cups glutinous rice flour"}, {"name": "1/2 cups coconut milk", "description": "1/2 cups coconut milk"}, {"name": "1/4 cup brown sugar", "description": "1/4 cup brown sugar"}, {"name": "1/8 tsp salt", "description": "1/8 tsp salt"}, {"name": "Banana leaves, wilted", "description": "Banana leaves, wilted"}, {"name": "Glutinous Rice Flour → rice flour + a little cornstarch", "description": "Glutinous Rice Flour → rice flour + a little cornstarch"}, {"name": "Coconut Milk → evaporated milk or fresh milk", "description": "Coconut Milk → evaporated milk or fresh milk"}, {"name": "Brown Sugar → white sugar", "description": "Brown Sugar → white sugar"}, {"name": "Banana Leaves → parchment paper for lining", "description": "Banana Leaves → parchment paper for lining"}]'::jsonb, '[{"title": "Step 1", "description": "Combine the glutinous rice flour, coconut milk, brown sugar, and salt."}, {"title": "Step 2", "description": "Cook over low heat while stirring continuously until thick."}, {"title": "Step 3", "description": "Prepare wilted banana leaves."}, {"title": "Step 4", "description": "Spoon portions of the mixture onto the leaves."}, {"title": "Step 5", "description": "Fold and wrap securely."}, {"title": "Step 6", "description": "Allow to cool completely."}, {"title": "Step 7", "description": "Serve at room temperature."}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.recipes (id, title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps) OVERRIDING SYSTEM VALUE
VALUES (116, 'Ube Cheese Pandesal Bread Pudding', 'Dessert', '30 min', 'Easy', '', '1 person', '430 kcal', NULL, '[{"name": "1.5 ube cheese pandesal, cubed", "description": "1.5 ube cheese pandesal, cubed"}, {"name": "1/2 eggs", "description": "1/2 eggs"}, {"name": "1/4 cup evaporated milk", "description": "1/4 cup evaporated milk"}, {"name": "1/8 cup condensed milk", "description": "1/8 cup condensed milk"}, {"name": "1/16 cup grated cheese", "description": "1/16 cup grated cheese"}, {"name": "1/4 tbsp melted butter", "description": "1/4 tbsp melted butter"}, {"name": "Cheese → quick-melt cheese or mild cheddar", "description": "Cheese → quick-melt cheese or mild cheddar"}, {"name": "Eggs → commercial egg substitute", "description": "Eggs → commercial egg substitute"}, {"name": "Evaporated Milk → fresh milk", "description": "Evaporated Milk → fresh milk"}, {"name": "Condensed Milk → evaporated milk + sugar", "description": "Condensed Milk → evaporated milk + sugar"}, {"name": "Butter → margarine", "description": "Butter → margarine"}]'::jsonb, '[{"title": "Step 1", "description": "Preheat the oven to 180°C (350°F)."}, {"title": "Step 2", "description": "Arrange the bread cubes in a greased baking dish."}, {"title": "Step 3", "description": "Whisk together the eggs, evaporated milk, and condensed milk."}, {"title": "Step 4", "description": "Pour the custard mixture over the bread."}, {"title": "Step 5", "description": "Sprinkle grated cheese on top."}, {"title": "Step 6", "description": "Bake for 30–35 minutes until golden and set."}, {"title": "Step 7", "description": "Serve warm."}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.recipes (id, title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps) OVERRIDING SYSTEM VALUE
VALUES (117, 'Macapuno Delight', 'Dessert', '30 min', 'Easy', '', '1 person', '520 kcal', NULL, '[{"name": "1/2 cups macapuno strings", "description": "1/2 cups macapuno strings"}, {"name": "1/4 cup all-purpose cream", "description": "1/4 cup all-purpose cream"}, {"name": "1/4 can condensed milk", "description": "1/4 can condensed milk"}, {"name": "1/8 cup nata de coco (optional)", "description": "1/8 cup nata de coco (optional)"}, {"name": "Maraschino cherries for garnish", "description": "Maraschino cherries for garnish"}, {"name": "Macapuno Strings → young coconut strips", "description": "Macapuno Strings → young coconut strips"}, {"name": "All-Purpose Cream → whipping cream or chilled evaporated milk", "description": "All-Purpose Cream → whipping cream or chilled evaporated milk"}, {"name": "Condensed Milk → evaporated milk + sugar", "description": "Condensed Milk → evaporated milk + sugar"}, {"name": "Nata De Coco → jelly cubes", "description": "Nata De Coco → jelly cubes"}]'::jsonb, '[{"title": "Step 1", "description": "Combine the all-purpose cream and condensed milk in a bowl."}, {"title": "Step 2", "description": "Add the macapuno strings and nata de coco."}, {"title": "Step 3", "description": "Fold gently until well mixed."}, {"title": "Step 4", "description": "Transfer to a serving container."}, {"title": "Step 5", "description": "Cover and refrigerate for at least 3 hours."}, {"title": "Step 6", "description": "Garnish with cherries before serving."}, {"title": "Step 7", "description": "Serve chilled."}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.recipes (id, title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps) OVERRIDING SYSTEM VALUE
VALUES (118, 'Saba con Crema', 'Dessert', '30 min', 'Easy', '', '1 person', '480 kcal', NULL, '[{"name": "1.5 sweetened saba bananas, sliced", "description": "1.5 sweetened saba bananas, sliced"}, {"name": "1/4 cup all-purpose cream", "description": "1/4 cup all-purpose cream"}, {"name": "1/8 cup condensed milk", "description": "1/8 cup condensed milk"}, {"name": "1/16 cup grated cheese (optional)", "description": "1/16 cup grated cheese (optional)"}, {"name": "Saba Bananas → ripe plantain", "description": "Saba Bananas → ripe plantain"}, {"name": "All-Purpose Cream → whipping cream or chilled evaporated milk", "description": "All-Purpose Cream → whipping cream or chilled evaporated milk"}, {"name": "Condensed Milk → evaporated milk + sugar", "description": "Condensed Milk → evaporated milk + sugar"}, {"name": "Cheese → quick-melt cheese or mild cheddar", "description": "Cheese → quick-melt cheese or mild cheddar"}]'::jsonb, '[{"title": "Step 1", "description": "Chill the all-purpose cream before mixing."}, {"title": "Step 2", "description": "Combine the cream and condensed milk in a bowl."}, {"title": "Step 3", "description": "Fold in the sliced saba bananas."}, {"title": "Step 4", "description": "Transfer to a serving dish."}, {"title": "Step 5", "description": "Sprinkle grated cheese on top if desired."}, {"title": "Step 6", "description": "Refrigerate for 2 hours."}, {"title": "Step 7", "description": "Serve chilled."}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.recipes (id, title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps) OVERRIDING SYSTEM VALUE
VALUES (119, 'Ube Pastillas', 'Dessert', '30 min', 'Easy', '', '1 person', '700 kcal', NULL, '[{"name": "1/2 cups powdered milk", "description": "1/2 cups powdered milk"}, {"name": "1/4 can condensed milk", "description": "1/4 can condensed milk"}, {"name": "1/8 cup ube halaya", "description": "1/8 cup ube halaya"}, {"name": "1/8 cup sugar", "description": "1/8 cup sugar"}, {"name": "Powdered Milk → milk powder", "description": "Powdered Milk → milk powder"}, {"name": "Condensed Milk → evaporated milk + sugar", "description": "Condensed Milk → evaporated milk + sugar"}, {"name": "Ube Halaya → mashed purple sweet potato + sugar", "description": "Ube Halaya → mashed purple sweet potato + sugar"}]'::jsonb, '[{"title": "Step 1", "description": "Combine the powdered milk, condensed milk, and ube halaya."}, {"title": "Step 2", "description": "Mix until a soft dough forms."}, {"title": "Step 3", "description": "Shape into small logs or balls."}, {"title": "Step 4", "description": "Roll each piece in sugar."}, {"title": "Step 5", "description": "Arrange on a tray."}, {"title": "Step 6", "description": "Chill for 30 minutes."}, {"title": "Step 7", "description": "Wrap individually before serving."}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.recipes (id, title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps) OVERRIDING SYSTEM VALUE
VALUES (120, 'Coffee Jelly', 'Dessert', '30 min', 'Easy', '', '1 person', '400 kcal', NULL, '[{"name": "1/4 pack unflavored gelatin", "description": "1/4 pack unflavored gelatin"}, {"name": "1/2 cups brewed strong coffee", "description": "1/2 cups brewed strong coffee"}, {"name": "1/8 cup sugar", "description": "1/8 cup sugar"}, {"name": "1/4 cup all-purpose cream", "description": "1/4 cup all-purpose cream"}, {"name": "1/8 cup condensed milk", "description": "1/8 cup condensed milk"}, {"name": "All-Purpose Cream → whipping cream or chilled evaporated milk", "description": "All-Purpose Cream → whipping cream or chilled evaporated milk"}, {"name": "Condensed Milk → evaporated milk + sugar", "description": "Condensed Milk → evaporated milk + sugar"}]'::jsonb, '[{"title": "Step 1", "description": "Dissolve the gelatin in the hot brewed coffee."}, {"title": "Step 2", "description": "Add the sugar and stir until dissolved."}, {"title": "Step 3", "description": "Pour into a mold and refrigerate until firm."}, {"title": "Step 4", "description": "Cut the coffee jelly into cubes."}, {"title": "Step 5", "description": "Mix the all-purpose cream and condensed milk."}, {"title": "Step 6", "description": "Fold the jelly cubes into the cream mixture."}, {"title": "Step 7", "description": "Chill before serving."}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.recipes (id, title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps) OVERRIDING SYSTEM VALUE
VALUES (121, 'Ube Leche Flan Cake', 'Dessert', '30 min', 'Medium', '', '1 person', '550 kcal', NULL, '[{"name": "1/4 prepared ube cake batter", "description": "1/4 prepared ube cake batter"}, {"name": "1/4 prepared leche flan", "description": "1/4 prepared leche flan"}, {"name": "1/2 eggs", "description": "1/2 eggs"}, {"name": "1/8 cup evaporated milk", "description": "1/8 cup evaporated milk"}, {"name": "Butter for greasing the pan", "description": "Butter for greasing the pan"}, {"name": "Eggs → commercial egg substitute", "description": "Eggs → commercial egg substitute"}, {"name": "Evaporated Milk → fresh milk", "description": "Evaporated Milk → fresh milk"}, {"name": "Butter → margarine", "description": "Butter → margarine"}]'::jsonb, '[{"title": "Step 1", "description": "Preheat the oven to 175°C (350°F)."}, {"title": "Step 2", "description": "Grease a round cake pan with butter."}, {"title": "Step 3", "description": "Pour the ube cake batter into the pan."}, {"title": "Step 4", "description": "Carefully place the prepared leche flan on top of the batter."}, {"title": "Step 5", "description": "Bake for 45–50 minutes or until a toothpick inserted into the cake comes out clean."}, {"title": "Step 6", "description": "Cool completely before inverting onto a serving plate."}, {"title": "Step 7", "description": "Slice and serve chilled or at room temperature."}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.recipes (id, title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps) OVERRIDING SYSTEM VALUE
VALUES (122, 'Mango Sago', 'Dessert', '30 min', 'Easy', '', '1 person', '420 kcal', NULL, '[{"name": "1/2 ripe mangoes, diced", "description": "1/2 ripe mangoes, diced"}, {"name": "1/4 cup cooked small sago pearls", "description": "1/4 cup cooked small sago pearls"}, {"name": "1/4 cup all-purpose cream", "description": "1/4 cup all-purpose cream"}, {"name": "1/8 cup condensed milk", "description": "1/8 cup condensed milk"}, {"name": "1/8 cup evaporated milk", "description": "1/8 cup evaporated milk"}, {"name": "Mangoes → ripe papaya or canned peaches", "description": "Mangoes → ripe papaya or canned peaches"}, {"name": "Sago Pearls → small tapioca pearls", "description": "Sago Pearls → small tapioca pearls"}, {"name": "All-Purpose Cream → whipping cream or chilled evaporated milk", "description": "All-Purpose Cream → whipping cream or chilled evaporated milk"}, {"name": "Condensed Milk → evaporated milk + sugar", "description": "Condensed Milk → evaporated milk + sugar"}, {"name": "Evaporated Milk → fresh milk", "description": "Evaporated Milk → fresh milk"}]'::jsonb, '[{"title": "Step 1", "description": "Cook the sago pearls according to the package instructions and drain."}, {"title": "Step 2", "description": "Combine the all-purpose cream, condensed milk, and evaporated milk."}, {"title": "Step 3", "description": "Add the cooked sago pearls and diced mangoes."}, {"title": "Step 4", "description": "Fold gently until well combined."}, {"title": "Step 5", "description": "Transfer to a serving bowl."}, {"title": "Step 6", "description": "Refrigerate for at least 2 hours."}, {"title": "Step 7", "description": "Serve chilled."}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.recipes (id, title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps) OVERRIDING SYSTEM VALUE
VALUES (123, 'Ube Mousse', 'Dessert', '30 min', 'Easy', '', '1 person', '500 kcal', NULL, '[{"name": "1/2 cups ube halaya", "description": "1/2 cups ube halaya"}, {"name": "1/2 cups whipped cream", "description": "1/2 cups whipped cream"}, {"name": "1/8 cup condensed milk", "description": "1/8 cup condensed milk"}, {"name": "1/4 tsp ube extract (optional)", "description": "1/4 tsp ube extract (optional)"}, {"name": "Ube Halaya → mashed purple sweet potato + sugar", "description": "Ube Halaya → mashed purple sweet potato + sugar"}, {"name": "Whipped Cream → whipped all-purpose cream", "description": "Whipped Cream → whipped all-purpose cream"}, {"name": "Condensed Milk → evaporated milk + sugar", "description": "Condensed Milk → evaporated milk + sugar"}, {"name": "Ube Extract → ube flavoring or omit", "description": "Ube Extract → ube flavoring or omit"}]'::jsonb, '[{"title": "Step 1", "description": "Beat the whipped cream until soft peaks form."}, {"title": "Step 2", "description": "In another bowl, combine the ube halaya and condensed milk."}, {"title": "Step 3", "description": "Fold the whipped cream into the ube mixture."}, {"title": "Step 4", "description": "Add the ube extract if desired."}, {"title": "Step 5", "description": "Spoon into serving glasses."}, {"title": "Step 6", "description": "Refrigerate for at least 3 hours."}, {"title": "Step 7", "description": "Serve chilled."}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.recipes (id, title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps) OVERRIDING SYSTEM VALUE
VALUES (124, 'Pineapple Macapuno Delight', 'Dessert', '30 min', 'Easy', '', '1 person', '520 kcal', NULL, '[{"name": "1/2 cups pineapple chunks, drained", "description": "1/2 cups pineapple chunks, drained"}, {"name": "1/4 cup macapuno strings", "description": "1/4 cup macapuno strings"}, {"name": "1/4 cup all-purpose cream", "description": "1/4 cup all-purpose cream"}, {"name": "1/4 can condensed milk", "description": "1/4 can condensed milk"}, {"name": "1/8 cup nata de coco", "description": "1/8 cup nata de coco"}, {"name": "Pineapple Chunks → canned peaches, drained", "description": "Pineapple Chunks → canned peaches, drained"}, {"name": "Macapuno Strings → young coconut strips", "description": "Macapuno Strings → young coconut strips"}, {"name": "All-Purpose Cream → whipping cream or chilled evaporated milk", "description": "All-Purpose Cream → whipping cream or chilled evaporated milk"}, {"name": "Condensed Milk → evaporated milk + sugar", "description": "Condensed Milk → evaporated milk + sugar"}, {"name": "Nata De Coco → jelly cubes", "description": "Nata De Coco → jelly cubes"}]'::jsonb, '[{"title": "Step 1", "description": "Drain the pineapple chunks thoroughly."}, {"title": "Step 2", "description": "Combine the pineapple, macapuno, and nata de coco in a bowl."}, {"title": "Step 3", "description": "Mix the all-purpose cream and condensed milk."}, {"title": "Step 4", "description": "Pour the cream mixture over the fruit."}, {"title": "Step 5", "description": "Fold gently until well combined."}, {"title": "Step 6", "description": "Chill for at least 3 hours."}, {"title": "Step 7", "description": "Serve cold."}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.recipes (id, title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps) OVERRIDING SYSTEM VALUE
VALUES (125, 'Langka Ice Cream', 'Dessert', '30 min', 'Easy', '', '1 person', '550 kcal', NULL, '[{"name": "1/2 cups ripe jackfruit, finely chopped", "description": "1/2 cups ripe jackfruit, finely chopped"}, {"name": "1/2 cups all-purpose cream", "description": "1/2 cups all-purpose cream"}, {"name": "1/4 can condensed milk", "description": "1/4 can condensed milk"}, {"name": "1/4 tsp vanilla extract", "description": "1/4 tsp vanilla extract"}, {"name": "Jackfruit → canned jackfruit, drained", "description": "Jackfruit → canned jackfruit, drained"}, {"name": "All-Purpose Cream → whipping cream or chilled evaporated milk", "description": "All-Purpose Cream → whipping cream or chilled evaporated milk"}, {"name": "Condensed Milk → evaporated milk + sugar", "description": "Condensed Milk → evaporated milk + sugar"}, {"name": "Vanilla Extract → vanilla essence or omit", "description": "Vanilla Extract → vanilla essence or omit"}]'::jsonb, '[{"title": "Step 1", "description": "Blend half of the jackfruit until smooth."}, {"title": "Step 2", "description": "Combine the blended jackfruit, chopped jackfruit, cream, condensed milk, and vanilla."}, {"title": "Step 3", "description": "Mix until well combined."}, {"title": "Step 4", "description": "Transfer to a freezer-safe container."}, {"title": "Step 5", "description": "Cover tightly."}, {"title": "Step 6", "description": "Freeze overnight."}, {"title": "Step 7", "description": "Scoop and serve."}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.recipes (id, title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps) OVERRIDING SYSTEM VALUE
VALUES (126, 'Sweet Potato Halaya', 'Dessert', '30 min', 'Easy', '', '1 person', '600 kcal', NULL, '[{"name": "1/4 kg sweet potatoes, boiled and mashed", "description": "1/4 kg sweet potatoes, boiled and mashed"}, {"name": "1/4 can condensed milk", "description": "1/4 can condensed milk"}, {"name": "1/4 cup coconut milk", "description": "1/4 cup coconut milk"}, {"name": "1/16 cup butter", "description": "1/16 cup butter"}, {"name": "1/8 cup sugar", "description": "1/8 cup sugar"}, {"name": "Sweet Potatoes → pumpkin or another sweet potato variety", "description": "Sweet Potatoes → pumpkin or another sweet potato variety"}, {"name": "Condensed Milk → evaporated milk + sugar", "description": "Condensed Milk → evaporated milk + sugar"}, {"name": "Coconut Milk → evaporated milk or fresh milk", "description": "Coconut Milk → evaporated milk or fresh milk"}, {"name": "Butter → margarine", "description": "Butter → margarine"}]'::jsonb, '[{"title": "Step 1", "description": "Combine the mashed sweet potatoes and coconut milk in a pan."}, {"title": "Step 2", "description": "Add the condensed milk and sugar."}, {"title": "Step 3", "description": "Cook over low heat while stirring continuously."}, {"title": "Step 4", "description": "Add the butter and continue stirring until thick."}, {"title": "Step 5", "description": "Transfer to a greased serving dish."}, {"title": "Step 6", "description": "Smooth the top with a spatula."}, {"title": "Step 7", "description": "Cool before serving."}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.recipes (id, title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps) OVERRIDING SYSTEM VALUE
VALUES (127, 'Pandan Jelly Delight', 'Dessert', '30 min', 'Easy', '', '1 person', '300 kcal', NULL, '[{"name": "1/4 pack pandan-flavored gelatin", "description": "1/4 pack pandan-flavored gelatin"}, {"name": "1/2 cups water", "description": "1/2 cups water"}, {"name": "1/4 cup all-purpose cream", "description": "1/4 cup all-purpose cream"}, {"name": "1/8 cup condensed milk", "description": "1/8 cup condensed milk"}, {"name": "1/4 cup nata de coco", "description": "1/4 cup nata de coco"}, {"name": "Pandan-Flavored Gelatin → unflavored gelatin + pandan extract", "description": "Pandan-Flavored Gelatin → unflavored gelatin + pandan extract"}, {"name": "All-Purpose Cream → whipping cream or chilled evaporated milk", "description": "All-Purpose Cream → whipping cream or chilled evaporated milk"}, {"name": "Condensed Milk → evaporated milk + sugar", "description": "Condensed Milk → evaporated milk + sugar"}, {"name": "Nata De Coco → jelly cubes", "description": "Nata De Coco → jelly cubes"}]'::jsonb, '[{"title": "Step 1", "description": "Prepare the pandan gelatin according to the package directions."}, {"title": "Step 2", "description": "Allow it to cool and set completely."}, {"title": "Step 3", "description": "Cut the jelly into cubes."}, {"title": "Step 4", "description": "Combine the cream and condensed milk."}, {"title": "Step 5", "description": "Fold in the jelly cubes and nata de coco."}, {"title": "Step 6", "description": "Chill for at least 2 hours."}, {"title": "Step 7", "description": "Serve cold."}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.recipes (id, title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps) OVERRIDING SYSTEM VALUE
VALUES (128, 'Caramel Banana Delight', 'Dessert', '30 min', 'Easy', '', '1 person', '650 kcal', NULL, '[{"name": "1.5 ripe saba bananas", "description": "1.5 ripe saba bananas"}, {"name": "1/8 cup brown sugar", "description": "1/8 cup brown sugar"}, {"name": "1/2 tbsp butter", "description": "1/2 tbsp butter"}, {"name": "1/4 cup whipped cream", "description": "1/4 cup whipped cream"}, {"name": "1/4 cup crushed graham crackers", "description": "1/4 cup crushed graham crackers"}, {"name": "Saba Bananas → ripe plantain", "description": "Saba Bananas → ripe plantain"}, {"name": "Brown Sugar → white sugar", "description": "Brown Sugar → white sugar"}, {"name": "Butter → margarine", "description": "Butter → margarine"}, {"name": "Whipped Cream → whipped all-purpose cream", "description": "Whipped Cream → whipped all-purpose cream"}, {"name": "Graham Crackers → digestive biscuits or plain cookies", "description": "Graham Crackers → digestive biscuits or plain cookies"}]'::jsonb, '[{"title": "Step 1", "description": "Slice the saba bananas into rounds."}, {"title": "Step 2", "description": "Melt the butter in a pan and add the brown sugar."}, {"title": "Step 3", "description": "Cook until the sugar caramelizes."}, {"title": "Step 4", "description": "Add the bananas and cook for 3–5 minutes."}, {"title": "Step 5", "description": "Allow the bananas to cool slightly."}, {"title": "Step 6", "description": "Layer the caramelized bananas, whipped cream, and crushed graham crackers in serving glasses."}, {"title": "Step 7", "description": "Chill for 1 hour before serving."}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.recipes (id, title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps) OVERRIDING SYSTEM VALUE
VALUES (129, 'Leche Flan', 'Dessert', '30 min', 'Medium', '', '1 person', '700 kcal', NULL, '[{"name": "2.5 egg yolks", "description": "2.5 egg yolks"}, {"name": "1/4 can (300ml) condensed milk", "description": "1/4 can (300ml) condensed milk"}, {"name": "1/4 can (370ml) evaporated milk", "description": "1/4 can (370ml) evaporated milk"}, {"name": "1/4 tsp vanilla extract", "description": "1/4 tsp vanilla extract"}, {"name": "1/4 cup white sugar (for caramel)", "description": "1/4 cup white sugar (for caramel)"}, {"name": "Egg Yolks → whole eggs, though the custard will be firmer", "description": "Egg Yolks → whole eggs, though the custard will be firmer"}, {"name": "Condensed Milk → evaporated milk + sugar", "description": "Condensed Milk → evaporated milk + sugar"}, {"name": "Evaporated Milk → fresh milk", "description": "Evaporated Milk → fresh milk"}, {"name": "Vanilla Extract → vanilla essence or omit", "description": "Vanilla Extract → vanilla essence or omit"}, {"name": "White Sugar → brown sugar", "description": "White Sugar → brown sugar"}]'::jsonb, '[{"title": "Step 1", "description": "Heat the sugar in a llanera over low heat until it melts into a golden caramel. Swirl to coat the bottom evenly and let it cool."}, {"title": "Step 2", "description": "In a bowl, whisk together the egg yolks, condensed milk, evaporated milk, and vanilla extract until smooth."}, {"title": "Step 3", "description": "Strain the mixture to remove bubbles and lumps."}, {"title": "Step 4", "description": "Pour the custard mixture into the prepared llanera."}, {"title": "Step 5", "description": "Cover tightly with aluminum foil."}, {"title": "Step 6", "description": "Steam over low heat for 35–40 minutes or until set."}, {"title": "Step 7", "description": "Cool completely, refrigerate for at least 4 hours, then invert onto a serving plate."}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.recipes (id, title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps) OVERRIDING SYSTEM VALUE
VALUES (130, 'Halo-Halo', 'Dessert', '30 min', 'Easy', '', '1 person', '450 kcal', NULL, '[{"name": "1/2 cups shaved ice", "description": "1/2 cups shaved ice"}, {"name": "1/16 cup sweetened saba bananas", "description": "1/16 cup sweetened saba bananas"}, {"name": "1/16 cup sweetened jackfruit", "description": "1/16 cup sweetened jackfruit"}, {"name": "1/16 cup nata de coco", "description": "1/16 cup nata de coco"}, {"name": "1/16 cup kaong", "description": "1/16 cup kaong"}, {"name": "1/16 cup sweetened red beans", "description": "1/16 cup sweetened red beans"}, {"name": "1/16 cup macapuno", "description": "1/16 cup macapuno"}, {"name": "1/4 slice leche flan", "description": "1/4 slice leche flan"}, {"name": "1/4 scoop ube ice cream", "description": "1/4 scoop ube ice cream"}, {"name": "1/8 cup evaporated milk", "description": "1/8 cup evaporated milk"}, {"name": "Saba Bananas → ripe plantain", "description": "Saba Bananas → ripe plantain"}, {"name": "Jackfruit → canned jackfruit, drained", "description": "Jackfruit → canned jackfruit, drained"}]'::jsonb, '[{"title": "Step 1", "description": "Place the sweetened fruits, beans, nata de coco, kaong, and macapuno into a tall glass."}, {"title": "Step 2", "description": "Fill the glass with shaved ice."}, {"title": "Step 3", "description": "Pour evaporated milk evenly over the ice."}, {"title": "Step 4", "description": "Top with a slice of leche flan."}, {"title": "Step 5", "description": "Add a scoop of ube ice cream."}, {"title": "Step 6", "description": "Garnish with additional sweetened fruits if desired."}, {"title": "Step 7", "description": "Mix well before eating."}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.recipes (id, title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps) OVERRIDING SYSTEM VALUE
VALUES (131, 'Mango Float', 'Dessert', '30 min', 'Easy', '', '1 person', '600 kcal', NULL, '[{"name": "1.5 ripe mangoes, sliced", "description": "1.5 ripe mangoes, sliced"}, {"name": "1/2 packs graham crackers", "description": "1/2 packs graham crackers"}, {"name": "1/2 cups all-purpose cream, chilled", "description": "1/2 cups all-purpose cream, chilled"}, {"name": "1/4 can condensed milk", "description": "1/4 can condensed milk"}, {"name": "Mangoes → ripe papaya or canned peaches", "description": "Mangoes → ripe papaya or canned peaches"}, {"name": "Graham Crackers → digestive biscuits or plain cookies", "description": "Graham Crackers → digestive biscuits or plain cookies"}, {"name": "All-Purpose Cream → whipping cream or chilled evaporated milk", "description": "All-Purpose Cream → whipping cream or chilled evaporated milk"}, {"name": "Condensed Milk → evaporated milk + sugar", "description": "Condensed Milk → evaporated milk + sugar"}]'::jsonb, '[{"title": "Step 1", "description": "Whip the chilled all-purpose cream until smooth."}, {"title": "Step 2", "description": "Fold in the condensed milk until well combined."}, {"title": "Step 3", "description": "Spread a thin layer of the cream mixture into a serving dish."}, {"title": "Step 4", "description": "Arrange graham crackers over the cream."}, {"title": "Step 5", "description": "Add another layer of cream followed by sliced mangoes."}, {"title": "Step 6", "description": "Repeat the layers until all ingredients are used."}, {"title": "Step 7", "description": "Refrigerate for at least 6 hours before serving."}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.recipes (id, title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps) OVERRIDING SYSTEM VALUE
VALUES (132, 'Buko Pandan', 'Dessert', '30 min', 'Easy', '', '1 person', '500 kcal', NULL, '[{"name": "1/2 cups young coconut strips", "description": "1/2 cups young coconut strips"}, {"name": "1/4 pack pandan-flavored jelly", "description": "1/4 pack pandan-flavored jelly"}, {"name": "1/2 cups water", "description": "1/2 cups water"}, {"name": "1/4 cup all-purpose cream", "description": "1/4 cup all-purpose cream"}, {"name": "1/4 can condensed milk", "description": "1/4 can condensed milk"}, {"name": "1/8 cup nata de coco", "description": "1/8 cup nata de coco"}, {"name": "Young Coconut → canned young coconut, drained", "description": "Young Coconut → canned young coconut, drained"}, {"name": "All-Purpose Cream → whipping cream or chilled evaporated milk", "description": "All-Purpose Cream → whipping cream or chilled evaporated milk"}, {"name": "Condensed Milk → evaporated milk + sugar", "description": "Condensed Milk → evaporated milk + sugar"}, {"name": "Nata De Coco → jelly cubes", "description": "Nata De Coco → jelly cubes"}]'::jsonb, '[{"title": "Step 1", "description": "Prepare the pandan jelly according to the package instructions and let it cool."}, {"title": "Step 2", "description": "Cut the jelly into small cubes."}, {"title": "Step 3", "description": "In a large bowl, combine the coconut strips, jelly cubes, and nata de coco."}, {"title": "Step 4", "description": "Mix the all-purpose cream with the condensed milk."}, {"title": "Step 5", "description": "Pour the cream mixture over the coconut mixture."}, {"title": "Step 6", "description": "Toss gently until evenly coated."}, {"title": "Step 7", "description": "Chill for at least 2 hours before serving."}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.recipes (id, title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps) OVERRIDING SYSTEM VALUE
VALUES (133, 'Cassava Cake', 'Dessert', '30 min', 'Medium', '', '1 person', '700 kcal', NULL, '[{"name": "1/4 kg grated cassava", "description": "1/4 kg grated cassava"}, {"name": "1/4 can condensed milk", "description": "1/4 can condensed milk"}, {"name": "1/4 can coconut milk", "description": "1/4 can coconut milk"}, {"name": "1/2 eggs", "description": "1/2 eggs"}, {"name": "1/8 cup sugar", "description": "1/8 cup sugar"}, {"name": "1/8 cup evaporated milk", "description": "1/8 cup evaporated milk"}, {"name": "Grated Cassava → frozen grated cassava, thawed and drained", "description": "Grated Cassava → frozen grated cassava, thawed and drained"}, {"name": "Condensed Milk → evaporated milk + sugar", "description": "Condensed Milk → evaporated milk + sugar"}, {"name": "Coconut Milk → evaporated milk or fresh milk", "description": "Coconut Milk → evaporated milk or fresh milk"}, {"name": "Eggs → commercial egg substitute", "description": "Eggs → commercial egg substitute"}, {"name": "Evaporated Milk → fresh milk", "description": "Evaporated Milk → fresh milk"}]'::jsonb, '[{"title": "Step 1", "description": "Preheat the oven to 180°C (350°F)."}, {"title": "Step 2", "description": "Mix the grated cassava, coconut milk, condensed milk, eggs, and sugar."}, {"title": "Step 3", "description": "Pour the mixture into a greased baking pan."}, {"title": "Step 4", "description": "Bake for 45 minutes."}, {"title": "Step 5", "description": "Mix the evaporated milk with a little condensed milk for the topping."}, {"title": "Step 6", "description": "Spread the topping over the cake and bake for another 15 minutes."}, {"title": "Step 7", "description": "Cool before slicing and serving."}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.recipes (id, title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps) OVERRIDING SYSTEM VALUE
VALUES (134, 'Ube Macapuno Salad', 'Dessert', '30 min', 'Easy', '', '1 person', '600 kcal', NULL, '[{"name": "1/2 cups ube halaya", "description": "1/2 cups ube halaya"}, {"name": "1/4 cup macapuno strings", "description": "1/4 cup macapuno strings"}, {"name": "1/4 cup nata de coco", "description": "1/4 cup nata de coco"}, {"name": "1/4 cup all-purpose cream", "description": "1/4 cup all-purpose cream"}, {"name": "1/4 can condensed milk", "description": "1/4 can condensed milk"}, {"name": "Ube Halaya → mashed purple sweet potato + sugar", "description": "Ube Halaya → mashed purple sweet potato + sugar"}, {"name": "Macapuno Strings → young coconut strips", "description": "Macapuno Strings → young coconut strips"}, {"name": "Nata De Coco → jelly cubes", "description": "Nata De Coco → jelly cubes"}, {"name": "All-Purpose Cream → whipping cream or chilled evaporated milk", "description": "All-Purpose Cream → whipping cream or chilled evaporated milk"}, {"name": "Condensed Milk → evaporated milk + sugar", "description": "Condensed Milk → evaporated milk + sugar"}]'::jsonb, '[{"title": "Step 1", "description": "Place the ube halaya in a large mixing bowl."}, {"title": "Step 2", "description": "Add the macapuno strings and nata de coco."}, {"title": "Step 3", "description": "Combine the all-purpose cream and condensed milk."}, {"title": "Step 4", "description": "Pour the cream mixture over the ube mixture."}, {"title": "Step 5", "description": "Fold gently until evenly mixed."}, {"title": "Step 6", "description": "Transfer to a serving container."}, {"title": "Step 7", "description": "Chill for at least 3 hours before serving."}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.recipes (id, title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps) OVERRIDING SYSTEM VALUE
VALUES (135, 'Mais con Yelo', 'Dessert', '30 min', 'Easy', '', '1 person', '220 kcal', NULL, '[{"name": "1/2 cups sweet corn kernels", "description": "1/2 cups sweet corn kernels"}, {"name": "1/2 cups crushed ice", "description": "1/2 cups crushed ice"}, {"name": "1/4 cup evaporated milk", "description": "1/4 cup evaporated milk"}, {"name": "1/16 cup sugar", "description": "1/16 cup sugar"}, {"name": "1/4 scoop vanilla ice cream (optional)", "description": "1/4 scoop vanilla ice cream (optional)"}, {"name": "Evaporated Milk → fresh milk", "description": "Evaporated Milk → fresh milk"}]'::jsonb, '[{"title": "Step 1", "description": "Place the sweet corn kernels into a tall glass."}, {"title": "Step 2", "description": "Fill the glass with crushed ice."}, {"title": "Step 3", "description": "Pour evaporated milk over the ice."}, {"title": "Step 4", "description": "Sprinkle with sugar."}, {"title": "Step 5", "description": "Add a scoop of vanilla ice cream if desired."}, {"title": "Step 6", "description": "Stir gently before serving."}, {"title": "Step 7", "description": "Enjoy immediately."}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.recipes (id, title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps) OVERRIDING SYSTEM VALUE
VALUES (136, 'Minatamis na Mais', 'Dessert', '30 min', 'Easy', '', '1 person', '500 kcal', NULL, '[{"name": "3/4 cups sweet corn kernels", "description": "3/4 cups sweet corn kernels"}, {"name": "1/2 cups coconut milk", "description": "1/2 cups coconut milk"}, {"name": "1/8 cup sugar", "description": "1/8 cup sugar"}, {"name": "1/16 tsp salt", "description": "1/16 tsp salt"}, {"name": "1/4 pandan leaf (optional)", "description": "1/4 pandan leaf (optional)"}, {"name": "Coconut Milk → evaporated milk or fresh milk", "description": "Coconut Milk → evaporated milk or fresh milk"}, {"name": "Pandan Leaf → pandan extract or vanilla", "description": "Pandan Leaf → pandan extract or vanilla"}]'::jsonb, '[{"title": "Step 1", "description": "Combine the coconut milk and pandan leaf in a saucepan."}, {"title": "Step 2", "description": "Bring to a gentle simmer over medium heat."}, {"title": "Step 3", "description": "Add the sweet corn kernels."}, {"title": "Step 4", "description": "Stir in the sugar and salt."}, {"title": "Step 5", "description": "Simmer for 10–15 minutes until the mixture thickens slightly."}, {"title": "Step 6", "description": "Remove the pandan leaf."}, {"title": "Step 7", "description": "Serve warm or chilled."}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.recipes (id, title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps) OVERRIDING SYSTEM VALUE
VALUES (137, 'Buko Pie', 'Dessert', '30 min', 'Medium', '', '1 person', '650 kcal', NULL, '[{"name": "1/2 pie crusts (top and bottom)", "description": "1/2 pie crusts (top and bottom)"}, {"name": "3/4 cups young coconut meat (buko), sliced", "description": "3/4 cups young coconut meat (buko), sliced"}, {"name": "1/4 cup evaporated milk", "description": "1/4 cup evaporated milk"}, {"name": "1/8 cup sugar", "description": "1/8 cup sugar"}, {"name": "1/16 cup cornstarch", "description": "1/16 cup cornstarch"}, {"name": "1/2 tbsp butter", "description": "1/2 tbsp butter"}, {"name": "1/4 egg, beaten (for egg wash)", "description": "1/4 egg, beaten (for egg wash)"}, {"name": "Pie Crust → store-bought pastry crust", "description": "Pie Crust → store-bought pastry crust"}, {"name": "Young Coconut → canned young coconut, drained", "description": "Young Coconut → canned young coconut, drained"}, {"name": "Evaporated Milk → fresh milk", "description": "Evaporated Milk → fresh milk"}, {"name": "Cornstarch → all-purpose flour", "description": "Cornstarch → all-purpose flour"}, {"name": "Butter → margarine", "description": "Butter → margarine"}]'::jsonb, '[{"title": "Step 1", "description": "Preheat the oven to 190°C (375°F)."}, {"title": "Step 2", "description": "In a saucepan, combine the evaporated milk, sugar, butter, and cornstarch until thick."}, {"title": "Step 3", "description": "Fold in the sliced young coconut and let the filling cool."}, {"title": "Step 4", "description": "Line a pie pan with the bottom crust and pour in the filling."}, {"title": "Step 5", "description": "Cover with the top crust and seal the edges."}, {"title": "Step 6", "description": "Brush the top with beaten egg."}, {"title": "Step 7", "description": "Bake for 40–45 minutes or until golden brown. Cool slightly before serving."}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.recipes (id, title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps) OVERRIDING SYSTEM VALUE
VALUES (138, 'Buko Salad', 'Dessert', '30 min', 'Easy', '', '1 person', '520 kcal', NULL, '[{"name": "3/4 cups young coconut strips", "description": "3/4 cups young coconut strips"}, {"name": "1/4 can fruit cocktail, drained", "description": "1/4 can fruit cocktail, drained"}, {"name": "1/4 cup nata de coco", "description": "1/4 cup nata de coco"}, {"name": "1/4 cup kaong", "description": "1/4 cup kaong"}, {"name": "1/4 cup all-purpose cream", "description": "1/4 cup all-purpose cream"}, {"name": "1/4 can condensed milk", "description": "1/4 can condensed milk"}, {"name": "1/8 cup shredded cheese (optional)", "description": "1/8 cup shredded cheese (optional)"}, {"name": "Young Coconut → canned young coconut, drained", "description": "Young Coconut → canned young coconut, drained"}, {"name": "Fruit Cocktail → mixed canned fruits", "description": "Fruit Cocktail → mixed canned fruits"}, {"name": "Nata De Coco → jelly cubes", "description": "Nata De Coco → jelly cubes"}, {"name": "Kaong → nata de coco", "description": "Kaong → nata de coco"}, {"name": "All-Purpose Cream → whipping cream or chilled evaporated milk", "description": "All-Purpose Cream → whipping cream or chilled evaporated milk"}]'::jsonb, '[{"title": "Step 1", "description": "Drain the fruit cocktail thoroughly."}, {"title": "Step 2", "description": "Combine the young coconut, fruit cocktail, nata de coco, and kaong in a large bowl."}, {"title": "Step 3", "description": "Mix the all-purpose cream and condensed milk."}, {"title": "Step 4", "description": "Pour the cream mixture over the fruits."}, {"title": "Step 5", "description": "Fold gently until well combined."}, {"title": "Step 6", "description": "Add shredded cheese if desired."}, {"title": "Step 7", "description": "Chill for at least 4 hours before serving."}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.recipes (id, title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps) OVERRIDING SYSTEM VALUE
VALUES (139, 'Mamon', 'Dessert', '30 min', 'Medium', '', '1 person', '500 kcal', NULL, '[{"name": "1/4 cups cake flour", "description": "1/4 cups cake flour"}, {"name": "1/4 tsp baking powder", "description": "1/4 tsp baking powder"}, {"name": "1 eggs", "description": "1 eggs"}, {"name": "3/16 cup sugar", "description": "3/16 cup sugar"}, {"name": "1/16 cup milk", "description": "1/16 cup milk"}, {"name": "1/16 cup melted butter", "description": "1/16 cup melted butter"}, {"name": "Grated cheese for topping", "description": "Grated cheese for topping"}, {"name": "Cake Flour → all-purpose flour", "description": "Cake Flour → all-purpose flour"}, {"name": "Eggs → commercial egg substitute", "description": "Eggs → commercial egg substitute"}, {"name": "Butter → margarine", "description": "Butter → margarine"}, {"name": "Cheese → quick-melt cheese or mild cheddar", "description": "Cheese → quick-melt cheese or mild cheddar"}]'::jsonb, '[{"title": "Step 1", "description": "Preheat the oven to 175°C (350°F)."}, {"title": "Step 2", "description": "Beat the eggs and sugar until light and fluffy."}, {"title": "Step 3", "description": "Fold in the flour and baking powder."}, {"title": "Step 4", "description": "Add the milk and melted butter."}, {"title": "Step 5", "description": "Pour into greased mamon molds."}, {"title": "Step 6", "description": "Bake for 18–20 minutes until lightly golden."}, {"title": "Step 7", "description": "Brush with butter and sprinkle with grated cheese before serving."}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.recipes (id, title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps) OVERRIDING SYSTEM VALUE
VALUES (140, 'Brazo de Mercedes', 'Dessert', '30 min', 'Medium', '', '1 person', '650 kcal', NULL, '[{"name": "2.5 egg whites", "description": "2.5 egg whites"}, {"name": "1/4 cup sugar", "description": "1/4 cup sugar"}, {"name": "1/4 tsp cream of tartar", "description": "1/4 tsp cream of tartar"}, {"name": "2.5 egg yolks", "description": "2.5 egg yolks"}, {"name": "1/4 can condensed milk", "description": "1/4 can condensed milk"}, {"name": "1/4 tsp vanilla extract", "description": "1/4 tsp vanilla extract"}, {"name": "Powdered sugar for dusting", "description": "Powdered sugar for dusting"}, {"name": "Egg Whites → commercial egg-white substitute", "description": "Egg Whites → commercial egg-white substitute"}, {"name": "Cream Of Tartar → lemon juice or vinegar", "description": "Cream Of Tartar → lemon juice or vinegar"}, {"name": "Egg Yolks → whole eggs, though the custard will be firmer", "description": "Egg Yolks → whole eggs, though the custard will be firmer"}, {"name": "Condensed Milk → evaporated milk + sugar", "description": "Condensed Milk → evaporated milk + sugar"}, {"name": "Vanilla Extract → vanilla essence or omit", "description": "Vanilla Extract → vanilla essence or omit"}]'::jsonb, '[{"title": "Step 1", "description": "Preheat the oven to 180°C (350°F)."}, {"title": "Step 2", "description": "Beat the egg whites with cream of tartar until foamy."}, {"title": "Step 3", "description": "Gradually add the sugar and continue beating until stiff peaks form."}, {"title": "Step 4", "description": "Spread the meringue evenly onto a lined baking tray."}, {"title": "Step 5", "description": "Bake for 20 minutes until lightly golden."}, {"title": "Step 6", "description": "Cook the egg yolks, condensed milk, and vanilla over low heat until thick, then cool."}, {"title": "Step 7", "description": "Spread the custard over the cooled meringue, roll tightly, and dust with powdered sugar."}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.recipes (id, title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps) OVERRIDING SYSTEM VALUE
VALUES (141, 'Ube Ice Cream', 'Dessert', '30 min', 'Easy', '', '1 person', '600 kcal', NULL, '[{"name": "1/2 cups ube halaya", "description": "1/2 cups ube halaya"}, {"name": "1/2 cups all-purpose cream", "description": "1/2 cups all-purpose cream"}, {"name": "1/4 can condensed milk", "description": "1/4 can condensed milk"}, {"name": "1/4 tsp ube extract (optional)", "description": "1/4 tsp ube extract (optional)"}, {"name": "Ube Halaya → mashed purple sweet potato + sugar", "description": "Ube Halaya → mashed purple sweet potato + sugar"}, {"name": "All-Purpose Cream → whipping cream or chilled evaporated milk", "description": "All-Purpose Cream → whipping cream or chilled evaporated milk"}, {"name": "Condensed Milk → evaporated milk + sugar", "description": "Condensed Milk → evaporated milk + sugar"}, {"name": "Ube Extract → ube flavoring or omit", "description": "Ube Extract → ube flavoring or omit"}]'::jsonb, '[{"title": "Step 1", "description": "Combine the ube halaya, all-purpose cream, and condensed milk in a blender."}, {"title": "Step 2", "description": "Add the ube extract if desired."}, {"title": "Step 3", "description": "Blend until smooth."}, {"title": "Step 4", "description": "Transfer the mixture to a freezer-safe container."}, {"title": "Step 5", "description": "Cover tightly."}, {"title": "Step 6", "description": "Freeze for at least 6 hours or overnight."}, {"title": "Step 7", "description": "Scoop and serve."}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.recipes (id, title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps) OVERRIDING SYSTEM VALUE
VALUES (142, 'Saging con Hielo', 'Dessert', '30 min', 'Easy', '', '1 person', '250 kcal', NULL, '[{"name": "1 sweetened saba bananas", "description": "1 sweetened saba bananas"}, {"name": "1/2 cups crushed ice", "description": "1/2 cups crushed ice"}, {"name": "1/4 cup evaporated milk", "description": "1/4 cup evaporated milk"}, {"name": "1/2 tbsp sugar", "description": "1/2 tbsp sugar"}, {"name": "1/4 tsp vanilla extract (optional)", "description": "1/4 tsp vanilla extract (optional)"}, {"name": "Saba Bananas → ripe plantain", "description": "Saba Bananas → ripe plantain"}, {"name": "Evaporated Milk → fresh milk", "description": "Evaporated Milk → fresh milk"}, {"name": "Vanilla Extract → vanilla essence or omit", "description": "Vanilla Extract → vanilla essence or omit"}]'::jsonb, '[{"title": "Step 1", "description": "Slice the sweetened saba bananas into serving glasses."}, {"title": "Step 2", "description": "Fill the glasses with crushed ice."}, {"title": "Step 3", "description": "Pour evaporated milk over the ice."}, {"title": "Step 4", "description": "Sprinkle with sugar."}, {"title": "Step 5", "description": "Add vanilla extract if desired."}, {"title": "Step 6", "description": "Stir gently."}, {"title": "Step 7", "description": "Serve immediately."}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.recipes (id, title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps) OVERRIDING SYSTEM VALUE
VALUES (143, 'Fruit Salad', 'Dessert', '30 min', 'Easy', '', '1 person', '500 kcal', NULL, '[{"name": "1/4 can fruit cocktail, drained", "description": "1/4 can fruit cocktail, drained"}, {"name": "1/4 cup nata de coco", "description": "1/4 cup nata de coco"}, {"name": "1/4 cup kaong", "description": "1/4 cup kaong"}, {"name": "1/4 cup all-purpose cream", "description": "1/4 cup all-purpose cream"}, {"name": "1/4 can condensed milk", "description": "1/4 can condensed milk"}, {"name": "1/8 cup shredded cheese (optional)", "description": "1/8 cup shredded cheese (optional)"}, {"name": "Fruit Cocktail → mixed canned fruits", "description": "Fruit Cocktail → mixed canned fruits"}, {"name": "Nata De Coco → jelly cubes", "description": "Nata De Coco → jelly cubes"}, {"name": "Kaong → nata de coco", "description": "Kaong → nata de coco"}, {"name": "All-Purpose Cream → whipping cream or chilled evaporated milk", "description": "All-Purpose Cream → whipping cream or chilled evaporated milk"}, {"name": "Condensed Milk → evaporated milk + sugar", "description": "Condensed Milk → evaporated milk + sugar"}, {"name": "Cheese → quick-melt cheese or mild cheddar", "description": "Cheese → quick-melt cheese or mild cheddar"}]'::jsonb, '[{"title": "Step 1", "description": "Drain the fruit cocktail completely."}, {"title": "Step 2", "description": "Combine the fruit cocktail, nata de coco, and kaong in a bowl."}, {"title": "Step 3", "description": "Mix the all-purpose cream and condensed milk together."}, {"title": "Step 4", "description": "Pour the cream mixture over the fruits."}, {"title": "Step 5", "description": "Fold gently until evenly coated."}, {"title": "Step 6", "description": "Add shredded cheese if desired."}, {"title": "Step 7", "description": "Refrigerate for at least 4 hours before serving."}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.recipes (id, title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps) OVERRIDING SYSTEM VALUE
VALUES (144, 'Maja Mais', 'Dessert', '30 min', 'Easy', '', '1 person', '450 kcal', NULL, '[{"name": "1/2 cups coconut milk", "description": "1/2 cups coconut milk"}, {"name": "1/4 cup evaporated milk", "description": "1/4 cup evaporated milk"}, {"name": "1/4 cup sweet corn kernels", "description": "1/4 cup sweet corn kernels"}, {"name": "3/16 cup sugar", "description": "3/16 cup sugar"}, {"name": "1/8 cup cornstarch", "description": "1/8 cup cornstarch"}, {"name": "1/8 cup water", "description": "1/8 cup water"}, {"name": "Toasted grated coconut for topping", "description": "Toasted grated coconut for topping"}, {"name": "Coconut Milk → evaporated milk or fresh milk", "description": "Coconut Milk → evaporated milk or fresh milk"}, {"name": "Evaporated Milk → fresh milk", "description": "Evaporated Milk → fresh milk"}, {"name": "Cornstarch → all-purpose flour", "description": "Cornstarch → all-purpose flour"}, {"name": "Grated Coconut → desiccated coconut", "description": "Grated Coconut → desiccated coconut"}]'::jsonb, '[{"title": "Step 1", "description": "In a saucepan, combine the coconut milk, evaporated milk, sugar, and sweet corn."}, {"title": "Step 2", "description": "Bring to a gentle simmer over medium heat."}, {"title": "Step 3", "description": "Dissolve the cornstarch in water."}, {"title": "Step 4", "description": "Slowly pour the slurry into the saucepan while stirring continuously."}, {"title": "Step 5", "description": "Cook until the mixture becomes thick and smooth."}, {"title": "Step 6", "description": "Transfer to a lightly greased serving dish and allow it to cool completely."}, {"title": "Step 7", "description": "Top with toasted grated coconut before serving."}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.recipes (id, title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps) OVERRIDING SYSTEM VALUE
VALUES (145, 'Minatamis na Saging', 'Dessert', '30 min', 'Easy', '', '1 person', '500 kcal', NULL, '[{"name": "2 ripe saba bananas, peeled", "description": "2 ripe saba bananas, peeled"}, {"name": "1/4 cup brown sugar", "description": "1/4 cup brown sugar"}, {"name": "3/4 cups water", "description": "3/4 cups water"}, {"name": "1/4 tsp vanilla extract (optional)", "description": "1/4 tsp vanilla extract (optional)"}, {"name": "1/4 pandan leaf (optional)", "description": "1/4 pandan leaf (optional)"}, {"name": "Saba Bananas → ripe plantain", "description": "Saba Bananas → ripe plantain"}, {"name": "Brown Sugar → white sugar", "description": "Brown Sugar → white sugar"}, {"name": "Vanilla Extract → vanilla essence or omit", "description": "Vanilla Extract → vanilla essence or omit"}, {"name": "Pandan Leaf → pandan extract or vanilla", "description": "Pandan Leaf → pandan extract or vanilla"}]'::jsonb, '[{"title": "Step 1", "description": "Combine the water, brown sugar, and pandan leaf in a pot."}, {"title": "Step 2", "description": "Bring the mixture to a boil until the sugar dissolves."}, {"title": "Step 3", "description": "Add the saba bananas."}, {"title": "Step 4", "description": "Simmer for 15–20 minutes until the bananas are tender."}, {"title": "Step 5", "description": "Add the vanilla extract if desired."}, {"title": "Step 6", "description": "Remove from the heat and let it cool slightly."}, {"title": "Step 7", "description": "Serve warm or chilled."}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.recipes (id, title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps) OVERRIDING SYSTEM VALUE
VALUES (146, 'Biko with Latik', 'Dessert', '30 min', 'Medium', '', '1 person', '650 kcal', NULL, '[{"name": "1/2 cups glutinous rice", "description": "1/2 cups glutinous rice"}, {"name": "3/4 cups coconut milk", "description": "3/4 cups coconut milk"}, {"name": "1/4 cups brown sugar", "description": "1/4 cups brown sugar"}, {"name": "1/8 tsp salt", "description": "1/8 tsp salt"}, {"name": "1/4 cup coconut cream (for latik)", "description": "1/4 cup coconut cream (for latik)"}, {"name": "Glutinous Rice → short-grain rice", "description": "Glutinous Rice → short-grain rice"}, {"name": "Coconut Milk → evaporated milk or fresh milk", "description": "Coconut Milk → evaporated milk or fresh milk"}, {"name": "Brown Sugar → white sugar", "description": "Brown Sugar → white sugar"}, {"name": "Coconut Cream → thick coconut milk or all-purpose cream", "description": "Coconut Cream → thick coconut milk or all-purpose cream"}]'::jsonb, '[{"title": "Step 1", "description": "Cook the glutinous rice until tender."}, {"title": "Step 2", "description": "In a separate pan, cook the coconut milk, brown sugar, and salt until slightly thick."}, {"title": "Step 3", "description": "Add the cooked rice and stir until fully coated."}, {"title": "Step 4", "description": "Transfer the mixture to a greased baking dish."}, {"title": "Step 5", "description": "Cook the coconut cream until it forms golden latik."}, {"title": "Step 6", "description": "Sprinkle the latik over the rice cake."}, {"title": "Step 7", "description": "Cool before slicing and serving."}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.recipes (id, title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps) OVERRIDING SYSTEM VALUE
VALUES (147, 'Pichi-Pichi with Cheese', 'Dessert', '30 min', 'Easy', '', '1 person', '400 kcal', NULL, '[{"name": "1/2 cups grated cassava", "description": "1/2 cups grated cassava"}, {"name": "1/4 cup sugar", "description": "1/4 cup sugar"}, {"name": "1/8 cup water", "description": "1/8 cup water"}, {"name": "1/4 tsp lye water", "description": "1/4 tsp lye water"}, {"name": "1/4 cup grated cheese", "description": "1/4 cup grated cheese"}, {"name": "Grated Cassava → frozen grated cassava, thawed and drained", "description": "Grated Cassava → frozen grated cassava, thawed and drained"}, {"name": "Lye Water → food-grade lye water is essential; do not substitute with household chemicals", "description": "Lye Water → food-grade lye water is essential; do not substitute with household chemicals"}, {"name": "Cheese → quick-melt cheese or mild cheddar", "description": "Cheese → quick-melt cheese or mild cheddar"}]'::jsonb, '[{"title": "Step 1", "description": "Combine the cassava, sugar, water, and lye water."}, {"title": "Step 2", "description": "Mix until well blended."}, {"title": "Step 3", "description": "Pour into greased molds."}, {"title": "Step 4", "description": "Steam for 35–40 minutes until translucent."}, {"title": "Step 5", "description": "Remove from the molds and allow to cool."}, {"title": "Step 6", "description": "Roll or sprinkle with grated cheese."}, {"title": "Step 7", "description": "Serve at room temperature."}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.recipes (id, title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps) OVERRIDING SYSTEM VALUE
VALUES (148, 'Binignit', 'Dessert', '30 min', 'Medium', '', '1 person', '600 kcal', NULL, '[{"name": "1/2 cups coconut milk", "description": "1/2 cups coconut milk"}, {"name": "1/4 cup coconut cream", "description": "1/4 cup coconut cream"}, {"name": "1/2 saba bananas, sliced", "description": "1/2 saba bananas, sliced"}, {"name": "1/4 cup sweet potatoes, cubed", "description": "1/4 cup sweet potatoes, cubed"}, {"name": "1/4 cup taro, cubed", "description": "1/4 cup taro, cubed"}, {"name": "1/8 cup cooked sago", "description": "1/8 cup cooked sago"}, {"name": "1/8 cup glutinous rice balls", "description": "1/8 cup glutinous rice balls"}, {"name": "1/8 cup brown sugar", "description": "1/8 cup brown sugar"}, {"name": "Coconut Milk → evaporated milk or fresh milk", "description": "Coconut Milk → evaporated milk or fresh milk"}, {"name": "Coconut Cream → thick coconut milk or all-purpose cream", "description": "Coconut Cream → thick coconut milk or all-purpose cream"}, {"name": "Saba Bananas → ripe plantain", "description": "Saba Bananas → ripe plantain"}, {"name": "Sweet Potatoes → pumpkin or another sweet potato variety", "description": "Sweet Potatoes → pumpkin or another sweet potato variety"}]'::jsonb, '[{"title": "Step 1", "description": "Bring the coconut milk to a gentle simmer."}, {"title": "Step 2", "description": "Add the sweet potatoes and taro."}, {"title": "Step 3", "description": "Cook until almost tender."}, {"title": "Step 4", "description": "Add the saba bananas, rice balls, and brown sugar."}, {"title": "Step 5", "description": "Stir in the cooked sago."}, {"title": "Step 6", "description": "Pour in the coconut cream and simmer for 5 minutes."}, {"title": "Step 7", "description": "Serve warm."}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.recipes (id, title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps) OVERRIDING SYSTEM VALUE
VALUES (149, 'Sinukmani', 'Dessert', '30 min', 'Medium', '', '1 person', '650 kcal', NULL, '[{"name": "1/2 cups glutinous rice", "description": "1/2 cups glutinous rice"}, {"name": "3/4 cups coconut milk", "description": "3/4 cups coconut milk"}, {"name": "1/41/2 cups brown sugar", "description": "1/41/2 cups brown sugar"}, {"name": "1/8 tsp salt", "description": "1/8 tsp salt"}, {"name": "Latik for topping", "description": "Latik for topping"}, {"name": "Glutinous Rice → short-grain rice", "description": "Glutinous Rice → short-grain rice"}, {"name": "Coconut Milk → evaporated milk or fresh milk", "description": "Coconut Milk → evaporated milk or fresh milk"}, {"name": "Brown Sugar → white sugar", "description": "Brown Sugar → white sugar"}, {"name": "Latik → toasted grated coconut", "description": "Latik → toasted grated coconut"}]'::jsonb, '[{"title": "Step 1", "description": "Cook the glutinous rice until tender."}, {"title": "Step 2", "description": "Heat the coconut milk with the brown sugar and salt."}, {"title": "Step 3", "description": "Add the cooked rice and stir continuously."}, {"title": "Step 4", "description": "Cook until thick and sticky."}, {"title": "Step 5", "description": "Transfer to a greased tray."}, {"title": "Step 6", "description": "Top with latik."}, {"title": "Step 7", "description": "Cool before slicing."}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.recipes (id, title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps) OVERRIDING SYSTEM VALUE
VALUES (150, 'Mais con yelo', 'Dessert', '30 min', 'Easy', '', '1 person', '220 kcal', NULL, '[{"name": "1/2 cups sweet corn kernels", "description": "1/2 cups sweet corn kernels"}, {"name": "1/2 cups shaved ice", "description": "1/2 cups shaved ice"}, {"name": "1/4 cup evaporated milk", "description": "1/4 cup evaporated milk"}, {"name": "1/16 cup sugar", "description": "1/16 cup sugar"}, {"name": "Crushed ice as needed", "description": "Crushed ice as needed"}, {"name": "Evaporated Milk → fresh milk", "description": "Evaporated Milk → fresh milk"}]'::jsonb, '[{"title": "Step 1", "description": "Place the sweet corn in serving glasses."}, {"title": "Step 2", "description": "Add the sugar."}, {"title": "Step 3", "description": "Fill the glasses with shaved ice."}, {"title": "Step 4", "description": "Pour the evaporated milk over the ice."}, {"title": "Step 5", "description": "Mix gently."}, {"title": "Step 6", "description": "Add more ice if needed."}, {"title": "Step 7", "description": "Serve immediately."}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.recipes (id, title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps) OVERRIDING SYSTEM VALUE
VALUES (151, 'Nilupak na Kamote', 'Dessert', '30 min', 'Easy', '', '1 person', '550 kcal', NULL, '[{"name": "1/4 kg sweet potatoes", "description": "1/4 kg sweet potatoes"}, {"name": "1/8 cup butter", "description": "1/8 cup butter"}, {"name": "1/8 cup sugar", "description": "1/8 cup sugar"}, {"name": "1/8 cup grated coconut", "description": "1/8 cup grated coconut"}, {"name": "1/16 cup condensed milk", "description": "1/16 cup condensed milk"}, {"name": "Sweet Potatoes → pumpkin or another sweet potato variety", "description": "Sweet Potatoes → pumpkin or another sweet potato variety"}, {"name": "Butter → margarine", "description": "Butter → margarine"}, {"name": "Grated Coconut → desiccated coconut", "description": "Grated Coconut → desiccated coconut"}, {"name": "Condensed Milk → evaporated milk + sugar", "description": "Condensed Milk → evaporated milk + sugar"}]'::jsonb, '[{"title": "Step 1", "description": "Boil the sweet potatoes until tender."}, {"title": "Step 2", "description": "Peel and mash while still warm."}, {"title": "Step 3", "description": "Add the butter, sugar, condensed milk, and grated coconut."}, {"title": "Step 4", "description": "Mix until smooth."}, {"title": "Step 5", "description": "Transfer to a serving platter."}, {"title": "Step 6", "description": "Shape with a spoon or mold."}, {"title": "Step 7", "description": "Serve warm or chilled."}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.recipes (id, title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps) OVERRIDING SYSTEM VALUE
VALUES (152, 'Kalamay Hati', 'Dessert', '30 min', 'Medium', '', '1 person', '500 kcal', NULL, '[{"name": "1/2 cups glutinous rice flour", "description": "1/2 cups glutinous rice flour"}, {"name": "1/2 cups coconut milk", "description": "1/2 cups coconut milk"}, {"name": "1/41/2 cups brown sugar", "description": "1/41/2 cups brown sugar"}, {"name": "1/8 tsp salt", "description": "1/8 tsp salt"}, {"name": "Banana leaves (optional)", "description": "Banana leaves (optional)"}, {"name": "Glutinous Rice Flour → rice flour + a little cornstarch", "description": "Glutinous Rice Flour → rice flour + a little cornstarch"}, {"name": "Coconut Milk → evaporated milk or fresh milk", "description": "Coconut Milk → evaporated milk or fresh milk"}, {"name": "Brown Sugar → white sugar", "description": "Brown Sugar → white sugar"}, {"name": "Banana Leaves → parchment paper for lining", "description": "Banana Leaves → parchment paper for lining"}]'::jsonb, '[{"title": "Step 1", "description": "Combine the glutinous rice flour, coconut milk, brown sugar, and salt in a saucepan."}, {"title": "Step 2", "description": "Cook over low heat while stirring continuously."}, {"title": "Step 3", "description": "Continue cooking until the mixture becomes thick and glossy."}, {"title": "Step 4", "description": "Prepare banana leaf-lined molds or serving containers."}, {"title": "Step 5", "description": "Spoon the mixture into the molds."}, {"title": "Step 6", "description": "Allow it to cool and firm up."}, {"title": "Step 7", "description": "Serve at room temperature."}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.recipes (id, title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps) OVERRIDING SYSTEM VALUE
VALUES (153, 'Nilupak na Saging', 'Dessert', '30 min', 'Easy', '', '1 person', '450 kcal', NULL, '[{"name": "2 ripe saba bananas", "description": "2 ripe saba bananas"}, {"name": "1/16 cup butter", "description": "1/16 cup butter"}, {"name": "1/8 cup sugar", "description": "1/8 cup sugar"}, {"name": "1/8 cup grated coconut", "description": "1/8 cup grated coconut"}, {"name": "1/16 cup condensed milk", "description": "1/16 cup condensed milk"}, {"name": "Saba Bananas → ripe plantain", "description": "Saba Bananas → ripe plantain"}, {"name": "Butter → margarine", "description": "Butter → margarine"}, {"name": "Grated Coconut → desiccated coconut", "description": "Grated Coconut → desiccated coconut"}, {"name": "Condensed Milk → evaporated milk + sugar", "description": "Condensed Milk → evaporated milk + sugar"}]'::jsonb, '[{"title": "Step 1", "description": "Boil the saba bananas until tender."}, {"title": "Step 2", "description": "Peel and mash the bananas while still warm."}, {"title": "Step 3", "description": "Add the butter, sugar, condensed milk, and grated coconut."}, {"title": "Step 4", "description": "Mix until smooth and well combined."}, {"title": "Step 5", "description": "Transfer to a serving plate."}, {"title": "Step 6", "description": "Shape with a spoon or mold if desired."}, {"title": "Step 7", "description": "Serve warm or chilled."}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.recipes (id, title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps) OVERRIDING SYSTEM VALUE
VALUES (154, 'Kutsinta with Yema Sauce', 'Dessert', '30 min', 'Medium', '', '1 person', '500 kcal', NULL, '[{"name": "1/2 cups all-purpose flour", "description": "1/2 cups all-purpose flour"}, {"name": "1/41/2 cups brown sugar", "description": "1/41/2 cups brown sugar"}, {"name": "3/4 cups water", "description": "3/4 cups water"}, {"name": "1/2 tsp lye water", "description": "1/2 tsp lye water"}, {"name": "1/8 tsp annatto powder", "description": "1/8 tsp annatto powder"}, {"name": "1/4 cup yema sauce", "description": "1/4 cup yema sauce"}, {"name": "All-Purpose Flour → cake flour", "description": "All-Purpose Flour → cake flour"}, {"name": "Brown Sugar → white sugar", "description": "Brown Sugar → white sugar"}, {"name": "Lye Water → food-grade lye water is essential; do not substitute with household chemicals", "description": "Lye Water → food-grade lye water is essential; do not substitute with household chemicals"}, {"name": "Annatto Powder → paprika", "description": "Annatto Powder → paprika"}]'::jsonb, '[{"title": "Step 1", "description": "Dissolve the brown sugar in water."}, {"title": "Step 2", "description": "Add the flour, lye water, and annatto powder."}, {"title": "Step 3", "description": "Mix until smooth."}, {"title": "Step 4", "description": "Pour into greased molds."}, {"title": "Step 5", "description": "Steam for 30–35 minutes."}, {"title": "Step 6", "description": "Allow to cool before removing from the molds."}, {"title": "Step 7", "description": "Serve drizzled with yema sauce."}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.recipes (id, title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps) OVERRIDING SYSTEM VALUE
VALUES (155, 'Ginataang Bilo-Bilo with Langka', 'Dessert', '30 min', 'Medium', '', '1 person', '650 kcal', NULL, '[{"name": "1/2 cups coconut milk", "description": "1/2 cups coconut milk"}, {"name": "1/4 cup coconut cream", "description": "1/4 cup coconut cream"}, {"name": "1/4 cup glutinous rice balls", "description": "1/4 cup glutinous rice balls"}, {"name": "1/2 saba bananas, sliced", "description": "1/2 saba bananas, sliced"}, {"name": "1/4 cup sweet potatoes, cubed", "description": "1/4 cup sweet potatoes, cubed"}, {"name": "1/4 cup ripe jackfruit, sliced", "description": "1/4 cup ripe jackfruit, sliced"}, {"name": "1/8 cup brown sugar", "description": "1/8 cup brown sugar"}, {"name": "1/8 cup cooked sago pearls", "description": "1/8 cup cooked sago pearls"}, {"name": "Coconut Milk → evaporated milk or fresh milk", "description": "Coconut Milk → evaporated milk or fresh milk"}, {"name": "Coconut Cream → thick coconut milk or all-purpose cream", "description": "Coconut Cream → thick coconut milk or all-purpose cream"}, {"name": "Glutinous Rice Balls → small rice-flour balls", "description": "Glutinous Rice Balls → small rice-flour balls"}, {"name": "Saba Bananas → ripe plantain", "description": "Saba Bananas → ripe plantain"}]'::jsonb, '[{"title": "Step 1", "description": "Bring the coconut milk to a gentle simmer."}, {"title": "Step 2", "description": "Add the sweet potatoes and cook until almost tender."}, {"title": "Step 3", "description": "Add the glutinous rice balls and cook until they float."}, {"title": "Step 4", "description": "Stir in the saba bananas, jackfruit, and brown sugar."}, {"title": "Step 5", "description": "Add the cooked sago pearls."}, {"title": "Step 6", "description": "Pour in the coconut cream and simmer for 3–5 minutes."}, {"title": "Step 7", "description": "Serve warm."}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.recipes (id, title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps) OVERRIDING SYSTEM VALUE
VALUES (156, 'Candied Kamote', 'Dessert', '30 min', 'Easy', '', '1 person', '500 kcal', NULL, '[{"name": "1 medium sweet potatoes, peeled and sliced", "description": "1 medium sweet potatoes, peeled and sliced"}, {"name": "1/4 cup brown sugar", "description": "1/4 cup brown sugar"}, {"name": "1/2 cups water", "description": "1/2 cups water"}, {"name": "1/2 tbsp butter", "description": "1/2 tbsp butter"}, {"name": "1/4 tsp vanilla extract", "description": "1/4 tsp vanilla extract"}, {"name": "Sweet Potatoes → pumpkin or another sweet potato variety", "description": "Sweet Potatoes → pumpkin or another sweet potato variety"}, {"name": "Brown Sugar → white sugar", "description": "Brown Sugar → white sugar"}, {"name": "Butter → margarine", "description": "Butter → margarine"}, {"name": "Vanilla Extract → vanilla essence or omit", "description": "Vanilla Extract → vanilla essence or omit"}]'::jsonb, '[{"title": "Step 1", "description": "Bring the water and brown sugar to a boil."}, {"title": "Step 2", "description": "Add the sliced sweet potatoes."}, {"title": "Step 3", "description": "Simmer until tender."}, {"title": "Step 4", "description": "Stir in the butter and vanilla extract."}, {"title": "Step 5", "description": "Continue cooking until the syrup thickens."}, {"title": "Step 6", "description": "Remove from the heat."}, {"title": "Step 7", "description": "Serve warm."}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.recipes (id, title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps) OVERRIDING SYSTEM VALUE
VALUES (157, 'Leche Flan de Coco', 'Dessert', '30 min', 'Medium', '', '1 person', '650 kcal', NULL, '[{"name": "2.5 egg yolks", "description": "2.5 egg yolks"}, {"name": "1/4 can condensed milk", "description": "1/4 can condensed milk"}, {"name": "1/4 cup coconut milk", "description": "1/4 cup coconut milk"}, {"name": "1/4 tsp vanilla extract", "description": "1/4 tsp vanilla extract"}, {"name": "1/4 cup sugar (for caramel)", "description": "1/4 cup sugar (for caramel)"}, {"name": "Egg Yolks → whole eggs, though the custard will be firmer", "description": "Egg Yolks → whole eggs, though the custard will be firmer"}, {"name": "Condensed Milk → evaporated milk + sugar", "description": "Condensed Milk → evaporated milk + sugar"}, {"name": "Coconut Milk → evaporated milk or fresh milk", "description": "Coconut Milk → evaporated milk or fresh milk"}, {"name": "Vanilla Extract → vanilla essence or omit", "description": "Vanilla Extract → vanilla essence or omit"}]'::jsonb, '[{"title": "Step 1", "description": "Melt the sugar in a llanera until caramelized."}, {"title": "Step 2", "description": "Whisk together the egg yolks, condensed milk, coconut milk, and vanilla."}, {"title": "Step 3", "description": "Strain the mixture."}, {"title": "Step 4", "description": "Pour into the prepared llanera."}, {"title": "Step 5", "description": "Cover with foil and steam for 35–40 minutes."}, {"title": "Step 6", "description": "Cool completely before refrigerating."}, {"title": "Step 7", "description": "Invert onto a serving plate before serving."}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.recipes (id, title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps) OVERRIDING SYSTEM VALUE
VALUES (158, 'Cassava Custard Bars', 'Dessert', '30 min', 'Medium', '', '1 person', '450 kcal', NULL, '[{"name": "1/2 cups grated cassava", "description": "1/2 cups grated cassava"}, {"name": "1/4 cup coconut milk", "description": "1/4 cup coconut milk"}, {"name": "1/8 cup condensed milk", "description": "1/8 cup condensed milk"}, {"name": "1/2 eggs", "description": "1/2 eggs"}, {"name": "1/8 cup evaporated milk", "description": "1/8 cup evaporated milk"}, {"name": "1/16 cup sugar", "description": "1/16 cup sugar"}, {"name": "Grated Cassava → frozen grated cassava, thawed and drained", "description": "Grated Cassava → frozen grated cassava, thawed and drained"}, {"name": "Coconut Milk → evaporated milk or fresh milk", "description": "Coconut Milk → evaporated milk or fresh milk"}, {"name": "Condensed Milk → evaporated milk + sugar", "description": "Condensed Milk → evaporated milk + sugar"}, {"name": "Eggs → commercial egg substitute", "description": "Eggs → commercial egg substitute"}, {"name": "Evaporated Milk → fresh milk", "description": "Evaporated Milk → fresh milk"}]'::jsonb, '[{"title": "Step 1", "description": "Preheat the oven to 180°C (350°F)."}, {"title": "Step 2", "description": "Mix the cassava, coconut milk, condensed milk, and one egg."}, {"title": "Step 3", "description": "Pour into a greased baking pan and bake for 30 minutes."}, {"title": "Step 4", "description": "Mix the evaporated milk, sugar, and remaining egg."}, {"title": "Step 5", "description": "Pour the custard over the partially baked cassava."}, {"title": "Step 6", "description": "Bake for another 20 minutes until the top is set."}, {"title": "Step 7", "description": "Cool completely before slicing."}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.recipes (id, title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps) OVERRIDING SYSTEM VALUE
VALUES (159, 'Sweet Banana Rice Cups', 'Dessert', '30 min', 'Easy', '', '1 person', '500 kcal', NULL, '[{"name": "1/2 cups cooked glutinous rice", "description": "1/2 cups cooked glutinous rice"}, {"name": "3/4 ripe saba bananas, sliced", "description": "3/4 ripe saba bananas, sliced"}, {"name": "1/4 cup coconut milk", "description": "1/4 cup coconut milk"}, {"name": "1/8 cup brown sugar", "description": "1/8 cup brown sugar"}, {"name": "1/16 tsp salt", "description": "1/16 tsp salt"}, {"name": "Toasted coconut for topping", "description": "Toasted coconut for topping"}, {"name": "Glutinous Rice → short-grain rice", "description": "Glutinous Rice → short-grain rice"}, {"name": "Saba Bananas → ripe plantain", "description": "Saba Bananas → ripe plantain"}, {"name": "Coconut Milk → evaporated milk or fresh milk", "description": "Coconut Milk → evaporated milk or fresh milk"}, {"name": "Brown Sugar → white sugar", "description": "Brown Sugar → white sugar"}, {"name": "Toasted Coconut → toasted desiccated coconut", "description": "Toasted Coconut → toasted desiccated coconut"}]'::jsonb, '[{"title": "Step 1", "description": "Heat the coconut milk, brown sugar, and salt in a saucepan."}, {"title": "Step 2", "description": "Add the cooked glutinous rice and stir until coated."}, {"title": "Step 3", "description": "Fold in the sliced saba bananas."}, {"title": "Step 4", "description": "Cook for 3–5 minutes."}, {"title": "Step 5", "description": "Spoon the mixture into serving cups."}, {"title": "Step 6", "description": "Sprinkle with toasted coconut."}, {"title": "Step 7", "description": "Serve warm or chilled."}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.recipes (id, title, category, "time", difficulty, image_url, serving, calories, background_color, ingredients, steps) OVERRIDING SYSTEM VALUE
VALUES (160, 'Puto Flan', 'Dessert', '30 min', 'Medium', '', '1 person', '500 kcal', NULL, '[{"name": "1/2 cups puto batter", "description": "1/2 cups puto batter"}, {"name": "1/4 prepared leche flan", "description": "1/4 prepared leche flan"}, {"name": "Butter for greasing the molds", "description": "Butter for greasing the molds"}, {"name": "Butter → margarine", "description": "Butter → margarine"}]'::jsonb, '[{"title": "Step 1", "description": "Grease the puto molds with butter."}, {"title": "Step 2", "description": "Fill each mold halfway with puto batter."}, {"title": "Step 3", "description": "Place a small slice of leche flan on top."}, {"title": "Step 4", "description": "Cover with a thin layer of puto batter."}, {"title": "Step 5", "description": "Steam for 15–20 minutes or until cooked."}, {"title": "Step 6", "description": "Cool for a few minutes before removing from the molds."}, {"title": "Step 7", "description": "Serve warm or chilled."}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

-- Reseat identity sequence after filling gaps
SELECT setval('public.recipes_id_seq', (SELECT MAX(id) FROM public.recipes));
